### ISSUE TITLE
Extension Doesn't Wait for NVM to Instantiate

### ISSUE THREAD

**Issue by mattwaler** [fwouts/previewjs#1032]
### Describe the bug

I can't use this extension because I use nvm to manage my global node installations, which takes a few seconds to initialize when a terminal window is opened. The extension just keeps telling me node is not installed.

### Reproduction

Open VS code with NVM installed, not node globally.

### Preview.js version

1.13.0

### Framework

React

### System Info

```shell
MacOS
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hey @mattwaler, thanks for taking the time to file this issue!

I'm using NVM myself, I haven't seen a lag like you mention before. I have a couple of questions to try to narrow down the issue:
- Which shell are you using? Open VS Code terminal with Ctrl+Shift+\` and run `echo $SHELL`.
- What does `type node` show in a VS Code terminal tab?
- Would you be able to share how NVM is loaded in your shell (likely in `.zshrc` or `.bashrc`)?

**Comment by mattwaler** [comment]
Yeah, multiple times! I still get the same "Node not found" error in the Extensions output.

**Comment by fwouts** [comment]
Cheers, I'll see if I can figure out a fix.

I might end up asking you to compile the extension locally to verify the fix before I roll it out to everyone, likely in a few days. Would that be OK?

**Comment by mattwaler** [comment]
I'd be happy to!

**Comment by fwouts** [comment]
That's a timely answer, I just might have a fix candidate for you to test.

Here are instructions to try it out locally:
```sh
$ git clone git@github.com:fwouts/previewjs
$ git checkout nvm-better #  yes, I know I could name my branches better... No pun intended!
$ pnpm install # see https://pnpm.io/installation if you don't already have pnpm
$ pnpm turbo run build --scope=@previewjs/core # build everything
$ cd integrations/vscode
$ pnpm dev:community # build VS Code extension and install it locally
```

You should then be able to reload VS Code and hopefully Preview.js will start working.

**Comment by mattwaler** [comment]
Sorry for the delay, I got COVID and I'm finally healthy enough to get back to development stuff. I followed these instructions and whatever you did fixed it for me!

![SCR-20221002-ee5](https://user-images.githubusercontent.com/32300026/193459012-6e2e0def-9386-4ac4-b9ef-464866699cf3.png)

**Comment by fwouts** [comment]
Awesome! And glad you got better.

I'll merge and release this once I've double checked that it doesn't break on Windows 👍

**Comment by mattwaler** [comment]
Just wanted to let you know that I also tested with some lazy loading zsh scripts and it still works in those cases as well, I'll throw the code below here to illustrate:

```zsh
lazynvm() {
  unset -f nvm node npm npx
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  if [ -f "$NVM_DIR/bash_completion" ]; then
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  fi
  if [[ -f .nvmrc && -r .nvmrc ]]; then
    echo "Using .nvmrc file"
    nvm i
  elif [[ $(nvm version) != $(nvm version default)  ]]; then
    echo "Using default nvm"
    nvm use default
  fi
}

node() {
  lazynvm
  node $@
}

npm() {
  lazynvm
  npm $@
}

npx() {
  lazynvm
  npx $@
}

nvm() {
  lazynvm
  nvm $@
}
```

**Comment by fwouts** [comment]
Hey @mattwaler, this should now be fixed in Preview.js v1.14, I think VS Code will automatically upgrade to the newest version if you have the current dev version :) Thanks a lot for your help!
