### ISSUE TITLE
Solid universal

### ISSUE THREAD

**Issue by elsassph** [fwouts/previewjs#1060]
**Is your feature request related to a problem? Please describe.**
I'm using Solid/universal, which means "bring your own render" function.
It's like using a custom Storybook preview.

**Describe the solution you'd like**
Maybe the previewjs config could allow providing a module to load for the render job.

**Describe alternatives you've considered**
Using Storybook where we can make a custom preview

**Additional context**

**Comment by fwouts** [comment]
Hey @elsassph, would you have a sample repo I could use to test with?

**Comment by fwouts** [comment]
Closing since no further info was provided.
