### ISSUE TITLE
Props editor autocomplete

### ISSUE THREAD

**Issue by jsBlackBelt** [fwouts/previewjs#111]
**Is your feature request related to a problem? Please describe.**
It would be awesome to have the props editor inspect the component props type and then it could suggest (auto complete) required and optional props instead of free text

**Describe the solution you'd like**
Props editor can inspect props interface and suggest instead of free text which is error prone

**Comment by fwouts** [comment]
Hey @jsBlackBelt, thanks for the suggestion.

I plan to offer this functionality in Preview.js Pro, which should hopefully come out in a few weeks!

**Comment by fwouts** [comment]
Hi @jsBlackBelt, this is now available, no need for the Pro version :)

**Comment by jsBlackBelt** [comment]
Awesome! Thanks @fwouts
