### ISSUE TITLE
Importing .scss file in Wrapper doesn't work

### ISSUE THREAD

**Issue by dsibinski** [fwouts/previewjs#1136]
### Describe the bug

Hi!
I'm using Sass for CSS processing in my React app. I use parcel and .scss works [without any additional configuration](https://parceljs.org/languages/sass/). 
I use PreviewJS in VS Code. I have one global file with styles: `styles.scss`.

In my global `Layout` component (production one), I import the file as follows:

```ts
import "./styles.scss";
```

Now I wanted to use this global styling file in PreviewJS. So I created the `__previewjs__\Wrapper.tsx` file and added the import as follows:

```ts
import "./src/components/Layout/styles.scss";
```

but the PreviewJS gives the following errors in the console:
```
[12:16:53 PM] Failed to reload /__previewjs__/Wrapper.tsx. This could be due to syntax errors or importing non-existent modules.
```

### Reproduction

Try importing an .scss file in PreviewJS's Wrapper.tsx file. See the issue

### Preview.js version

v2.2.5

### Framework

React 18.2.0

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 13.41 GB / 31.73 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.72.2 - C:\Users\dawid\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.3.32929.385 (Visual Studio Professional 2022)
  Browsers:
    Edge: Spartan (44.22621.675.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Preview logs (useful for rendering errors)

```shell
Failed to load resource: the server responded with a status of 404 (Not Found) styles.scss:1 
TypeError: Failed to fetch dynamically imported module: http://localhost:3140/preview/__previewjs__/Wrapper.tsx?t=1666685741752
(anonymous) @ logs.ts:7
```

**Comment by fwouts** [comment]
Hey @dsibinski, thanks for opening the issue!

At a quick glance, should your import start with `../` instead ?

**Comment by dsibinski** [comment]
@fwouts that was a good one 😀 Worked, how could I not notice that! Sorry :)

**Comment by fwouts** [comment]
No worries, in fact I've made that mistake myself. If you have suggestions to make it more obvious I'm all ears!
