### ISSUE TITLE
Preview not being detected / not showing

### ISSUE THREAD

**Issue by lainglo** [fwouts/previewjs#1138]
### Describe the bug

I have recently received a new laptop and I have installed Visual Studio Code on top of Ubuntu Studio (operating system), before installing preview.js extension. 

I have cloned repositories and tried to open files with components that I was successfully working on with preview.js on my old machine. These files that were working on my old machine but are not working on my new machine. I have even tried to open new files with react components in jsx and tsx. 

Unfortunately, in all cases, the "open in preview.js" link does not show, and when I click the preview.js icon it says "No compatible workspace detected from /...../bit-components/test/index.js from ..."

### Reproduction

1. Install Ubuntu Studio 22.04
2. Install vscode
3. Install preview.js extension
4. Open valid file/workspace

### Preview.js version

v1.16.1

### Framework

React 17.0.2

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 19.96 GB / 30.56 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.72.2 - /usr/bin/code
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 106.0.5249.119
    Firefox: 105.0.3
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
$ node --version
bash: cannot set terminal process group (2202): Inappropriate ioctl for device
bash: no job control in this shell
v16.14.0
✅ Detected compatible NodeJS version
🚀 Starting Preview.js server...
Streaming server logs to: /home/.../.vscode/extensions/zenclabs.previewjs-1.16.1/dist/server.log
If you experience any issues, please include this log file in bug reports.
✅ Preview.js server ready.

==========================================================================


[2022-10-25 14:23:40.502] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.previewjs, startup: false, activationEvent: 'onLanguage:javascript'

...

[2022-10-25 14:24:17.403] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.previewjs, startup: false, activationEvent: 'onStartupFinished'

...

[2022-10-25 14:32:23.745] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.previewjs, startup: false, activationEvent: 'onLanguage:typescriptreact'

...

[2022-10-25 14:36:49.764] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.previewjs, startup: false, activationEvent: 'onStartupFinished'
```

**Comment by lainglo** [comment]
Hi @fwouts 

Thanks for the response. Unfortunately the "new machine" I was using was stolen last week, so I am not faced with this problem anymore. It will be difficult for me to recreate the issue right now. I should get a new machine in the next few weeks (hopefully) or maybe by early next year so I may face this same issue in future.

However I have noticed a similar issue on my current machine. It will usually detect a react component but sometimes after a change/update to the component code it will lose the detection. At this point I can get it to work properly again just by closing and re-opening VS code. I will try to document this behaviour next time I notice it.

I think we can close the issue for now and I can reopen or create a new issue if I experience the problem again.

**Comment by fwouts** [comment]
Oh no, sorry to hear! 😰

Thanks, looking forward to more info from you.

**Comment by arendjr** [comment]
I'm having the same issue, but in a repository using Yarn PnP. Because of the setup we use there's no `node_modules`, so based on your comment it seems this might be supported yet... Any chance it could be though?

**Comment by fwouts** [comment]
Hey @arendjr, Yarn PnP is not supported, please refer to https://github.com/fwouts/previewjs/issues/846.
