### ISSUE TITLE
Preview.js needs NodeJS 14.18.0+ but running `node` failed with exit code 127.

### ISSUE THREAD

**Issue by safejace** [fwouts/previewjs#1140]
### Describe the bug

preview.js can't find node

### Reproduction

1. Go to component
2. see output tab

### Preview.js version

v1.16.1

### Framework

vue 3 nuxt 3

### System Info

```shell
..tbd

currently hanging...
```

### Used Package Manager

yarn

### Anything else?

```
$ node --version
sh: no job control in this shell
sh: node: command not found
Preview.js needs NodeJS 14.18.0+ but running `node` failed with exit code 127.

Is it installed? You may need to restart your IDE.

Preview.js server could not be started.
```

looks like its trying to run node from `sh`

i installed `node` via `nvm`. and i am using `zsh`

i wonder if the extension should have a setting for node path..?

**Comment by fwouts** [comment]
Hey @safejace, thanks for the bug report. NVM should work fine, but it looks like the extension doesn't detect your shell correctly.

Can you share the value of $SHELL in your VS Code terminal?

**Comment by safejace** [comment]
```
$ $SHELL
sh-3.2$ 
```

**Comment by safejace** [comment]
after setting vscode's default profile to zsh and restarted vscode.

works now. cheers
