### ISSUE TITLE
ConnectException crashes

### ISSUE THREAD

**Issue by gilbarbara** [fwouts/previewjs#117]
### Describe the bug

React Preview crashes repeatedly with this message:

```
React Preview crashed
.../Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/213.6461.79/WebStorm.app.plugins/react-preview/control-plane/control-plane.log
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:9120
```

### Reproduction

Open any React component WebStorm

### Preview.js version

0.7.2

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.03 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/1d/8tf6jr2d52d70mxt9snwwc7h0000gn/T/fnm_multishells/25216_1642478193631/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /var/folders/1d/8tf6jr2d52d70mxt9snwwc7h0000gn/T/fnm_multishells/25216_1642478193631/bin/npm
    Watchman: 2022.01.10.00 - /usr/local/bin/watchman
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    PhpStorm: 2021.3.1
    Sublime Text: 4121 - /usr/local/bin/subl
    VSCode: 1.63.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/local/bin/vim
    WebStorm: 2021.3.1
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 97.0.4692.71
    Chrome Canary: 99.0.4828.0
    Edge: 97.0.1072.62
    Firefox: 96.0
    Firefox Developer Edition: 94.0
    Safari: 15.2
```

### Used Package Manager

npm

### Preview.js control-plane.log (useful for crashes)

```shell
(eval):1: can't change option: zle
```

**Comment by fwouts** [comment]
Hey @gilbarbara, thanks for the report.

Would you be able to try Preview.js from previewjs.com and let me know if you're also experiencing this crash (and include logs if you do)? It doesn't yet have all the features of React Preview but I'm getting there slowly 🙂

**Comment by gilbarbara** [comment]
hey @fwouts 

I've installed the Preview.js plugin but it isn't showing the "Open in Preview.js" on my React components, even with preview.config.js file. Do. I need to config something else?

Thanks

**Comment by fwouts** [comment]
Hey @gilbarbara, thanks a lot for trying. I'm not sure what's happening here yet, but I'm investigating. Sorry I'm a bit slow these days, I have a newborn at home so work is getting quite disrupted!

**Comment by gilbarbara** [comment]
Hey @fwouts no problem, happy to help. Take your time!

**Comment by fwouts** [comment]
Hi @gilbarbara, Preview.js v1.0.4 is now available with improved logging which should help figure out what's going wrong. Would you mind trying it out?

**Comment by gilbarbara** [comment]
@fwouts Already on it! I'll try it out later today.
