### ISSUE TITLE
Allow mocking builtin browser methods/namespaces

### ISSUE THREAD

**Issue by jordanarldt** [fwouts/previewjs#1198]
**Is your feature request related to a problem? Please describe.**
Yes. I'm working on a Chrome Extension and I'm using React and PreviewJS to maximize my productivity, but when using the Chromium API, I'm unable to mock the methods, so after I've started using the chrome API, I can no longer use PreviewJS.

**Describe the solution you'd like**
I would like to be able to mock browser functions - in my case, the Chrome API (e.g. `chrome.tabs.query(...)`).

The reason this does not work with the current functionality is because the Chrome API is not imported anywhere, it is built-in natively to Chrome extensions; because of this, I cannot create a module alias for something that isn't being imported.

**Describe alternatives you've considered**
A workaround I just thought of is that I could wrap all my Chrome API usage in separate modules, and then mock those modules instead.

Thanks again @fwouts for the amazing plugin!

**Additional context**
n/a

**Comment by fwouts** [comment]
Hey @jordanarldt, thanks for the report! I can relate, having built a React-based Chrome extension before :)

Have you already tried adding this in `__previewjs__/Wrapper.tsx`:

```tsx
window.chrome = {
  tabs: {
    ... // your mock code
  }
};
```

**Comment by jordanarldt** [comment]
> Hey @jordanarldt, thanks for the report! I can relate, having built a React-based Chrome extension [before](https://github.com/fwouts/prmonitor) :)
> 
> Have you already tried adding this in `__previewjs__/Wrapper.tsx`:
> 
> ```tsx
> window.chrome = {
>   tabs: {
>     ... // your mock code
>   }
> };
> ```

@fwouts Oh man, I feel like an idiot. I thought I tried that already, but sure enough it works xD

That brings me to a separate question/request, is it possible to do wildcard aliases? Maybe something like this?
```
/** @type {import("@previewjs/config").PreviewConfig} */
module.exports = {
  alias: {
    "**/*/mockedModule": "mocks/mockedModule.js",
  },
};
```

The reason I can see this being useful is if I wanted to mock a file that doesn't have a path alias, so the potential path could be various things like:
```
import something from "../lib/someModule";

// and in another file:
import something from "../../lib/someModule";
```

**Comment by fwouts** [comment]
> > Hey @jordanarldt, thanks for the report! I can relate, having built a React-based Chrome extension [before](https://github.com/fwouts/prmonitor) :)
> > Have you already tried adding this in `__previewjs__/Wrapper.tsx`:
> > ```tsx
> > window.chrome = {
> >   tabs: {
> >     ... // your mock code
> >   }
> > };
> > ```
> 
> @fwouts Oh man, I feel like an idiot. I thought I tried that already, but sure enough it works xD
> 
> That brings me to a separate question/request, is it possible to do wildcard aliases? Maybe something like this?
> 
> ```
> /** @type {import("@previewjs/config").PreviewConfig} */
> module.exports = {
>   alias: {
>     "**/*/mockedModule": "mocks/mockedModule.js",
>   },
> };
> ```
> 
> The reason I can see this being useful is if I wanted to mock a file that doesn't have a path alias, so the potential path could be various things like:
> 
> ```
> import something from "../lib/someModule";
> 
> // and in another file:
> import something from "../../lib/someModule";
> ```

I'm not entirely sure I understand the question, but I think you might be able to make this work with a [custom Vite plugin](https://vitejs.dev/guide/api-plugin.html), like so:
```ts
// preview.config.js

module.exports = {
  vite: {
    plugins: [
      {
        name: "module-mocker",
        load(id) {
          if (id.endsWith('mockedModule')) {
            return fs.readFileSync("mocks/mockedModule.js", "utf8");
          }
        }
      }
    ]
  }
}
```

Would that work for you?

**Comment by jordanarldt** [comment]
@fwouts That seems like it might work, but ideally I'd like to prevent another dependency for such a specific use-case. I appreciate the help though, as always! :-) 

I'll go ahead and close this issue.

**Comment by fwouts** [comment]
@jordanarldt I think I understand your question better now, you should be able to just do:
```js
module.exports = {
  alias: {
    "src/lib/someModule": "mocks/mockedModule.js"
  }
};
```

and when this is exported as "./lib/someModule" from "src/foo.js" for example, it should correctly give you the mocked module :)

**Comment by fwouts** [comment]
Tested and nope, that doesn't work yet :) Will see if I can get it working.

**Comment by fwouts** [comment]
@jordanarldt I found the trick! You need an absolute path, like so:

```
module.exports = {
  alias: {
    "/src/lib/someModule.js": "mocked/mockedModule.js"
  }
};
```
