### ISSUE TITLE
Mock API requests from components

### ISSUE THREAD

**Issue by davidmeirlevy** [fwouts/previewjs#120]
**Is your feature request related to a problem? Please describe.**
My component is calling API from the same origin (my dev server proxy is handing it).
I would like to mock those request's responses.

**Describe the solution you'd like**
I bridge to MSW might help.

**Describe alternatives you've considered**
Easy way to add endpoints to the preview.js dev server.

**Additional context**
Right now, any request to the dev server returns an error object with status 200.
It's not helpful. :/

**Comment by fwouts** [comment]
Hey @davidmeirlevy, thanks for the suggestion.

Have you already tried the approach mentioned in this thread? https://github.com/zenclabs/previewjs/discussions/54#discussioncomment-1456814
