### ISSUE TITLE
ComponentStory stories aren't detected

### ISSUE THREAD

**Issue by fwouts** [fwouts/previewjs#1267]
See https://github.com/sanyuan0704/vite-storybook-starter repo for example (Button.stories.tsx).

**Comment by fwouts** [comment]
The issue was that the wrong version of `@storybook/csf` was being used. Upgrading it to v0.0.2 fixed it.

**Comment by fwouts** [comment]
Hey @dohooo, this should now work in v1.17.0 even when you don't upgrade `@storybook/csf` :)

**Comment by dohooo** [comment]
cool！
