### ISSUE TITLE
No compatible workspace detected from /Users/....

### ISSUE THREAD

**Issue by dcdb723** [fwouts/previewjs#1282]
### Describe the bug

When I use Preview for my js files, it always shows me the hint "No compatible workspace detected from /Users/victor/Documents/....../script.js"

### Reproduction

...

### Preview.js version

v1.16.1

### Framework

no framework

### System Info

```shell
MacOS ventura
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hey @dcdb723, thanks for reporting.

We should probably disable this warning for individual files since it wouldn't make sense to preview components in this context!

**Comment by fwouts** [comment]
Fix is now live in v1.17.0.

**Comment by fwouts** [comment]
@ZuhanLin would you be able to attach a screenshot?

**Comment by Hamoonist** [comment]
I have same problem, when I restart my computer, 1 out 5 times it works. But usually I get the same error, and it doesn't work.

**Comment by Hamoonist** [comment]
My best guess is something happened when I tried to install Storybook.js. before that I never had any issues, now it doesn't work at all

**Comment by fwouts** [comment]
Hey @Hamoonist, can you try deleting `node_modules/.previewjs` in your project and see if that solves anything? You can run `killall node` to make sure that Preview.js is definitely dead before you restart VS Code.

This definitely isn't a long-term fix, but if it works that's a good hint!

**Comment by Hamoonist** [comment]
Hey I just came here to tell you it's just working now :D 
If it happens again, I will try those and let you.
Btw, my free trial is over and I am going to purchase it, because even though it is still buggy, but it has definitely made my life easier!!
So, thank you for creating this!
