### ISSUE TITLE
vite plugin vue 2 is deprecated in profit of official plugin https://github.com/vitejs/vite-plugin-vue2

### ISSUE THREAD

**Issue by achretien** [fwouts/previewjs#1320]
### Describe the bug

I can't start previewjs because I have the official vite vue 2 plugin.

the config loaded in the server show two vue 2 plugins:

- the official one
- the old one you have in the config (both name are different so the plugin is not exclude)

### Reproduction

- have a VITE + VUE2 project using the https://github.com/vitejs/vite-plugin-vue2 in the vite.config file
- try to start the cli or the ide preview

### Preview.js CLI version

1.17.0

### Framework

Vue 2.7

### System Info

```shell
not working

- osx
- phpstorm
- node 18
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Thanks for bringing this up! Should be fixed in the next release in the coming week (hopefully).
