### ISSUE TITLE
[Sevelkit (version: 1.0.1)] previewjs can not start to render but stay  in loading forever )

### ISSUE THREAD

**Issue by Moon-DaeSeung** [fwouts/previewjs#1336]
### Describe the bug

![image](https://user-images.githubusercontent.com/64200419/211228261-0cda5067-d1da-46c2-b327-751bf76c3bbe.png)

Before I update sveltekit version (maybe 0.x.x -> 1.0.1), previewjs work well with svelte.
Now It doesn't work.. Perhaps due to new?? bundler in sveltekit 1.0.0

here is my packages.json
```
"devDependencies": {
    "@babel/core": "^7.20.2",
    "@playwright/test": "^1.25.0",
    "@types/jsdom": "^20.0.1",
    "@typescript-eslint/eslint-plugin": "^5.27.0",
    "@typescript-eslint/parser": "^5.27.0",
    "babel-loader": "^8.3.0",
    "eslint": "^8.16.0",
    "eslint-plugin-storybook": "^0.6.8",
    "eslint-plugin-svelte3": "^4.0.0",
    "prettier": "^2.8.1",
    "prettier-plugin-svelte": "^2.9.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "svelte": "^3.53.1",
    "svelte-check": "^2.7.1",
    "svelte-loader": "^3.1.4",
    "svelte-preprocess": "^4.10.6",
    "tslib": "^2.3.1",
    "typescript": "^4.7.4",
    "vite": "^3.1.0"
  },

```

### Reproduction

Create npm create svelte@next my-app
open my-app with vscdoe
 try it on any svelte file

### Preview.js version

v1.17.0

### Framework

Sveltekit 1.0.0

### System Info

```shell
sorry. this command does not work on my vscode terminal..
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hey @Moon-DaeSeung, which version of `@sveltejs/kit` do you use, and if you're only using 1.0.1 could you try 1.0.12 instead? You've only listed devDependencies here :)
