### ISSUE TITLE
Specify custom preview sizes

### ISSUE THREAD

**Issue by sr258** [fwouts/previewjs#135]
Currently, it looks like you have to resize the preview window manually to check the responsive behavior of a website. It would be great if there was a preset of window sizes that you can choose in the preview window. The custom previews could also include an option to override the default sizes.

**Comment by fwouts** [comment]
Hi @sr258, thanks for the suggestion!

This is a planned feature, but it will likely be part of Preview.js Pro, the paid version (trying to make the project sustainable). Hope that makes sense!

**Comment by fwouts** [comment]
Hi @sr258, this is now live :) https://previewjs.com/docs/features/viewports
