### ISSUE TITLE
Localhost refused to connect (Gitpod)

### ISSUE THREAD

**Issue by mmailaender** [fwouts/previewjs#1362]
### Describe the bug

We're using [Gitpod](https://gitpod.io/) for development. And if I try to use Preview.js I get "Localhost refused to connect"

![image](https://user-images.githubusercontent.com/87228994/219601778-90c3aedf-422f-485d-9bd4-c42af18e06da.png)

Gitpod is not directly exposing localhost. Instead, I get temporary URLs like this:
![image](https://user-images.githubusercontent.com/87228994/219601637-e4fa95b5-4a92-4cbf-8050-eb822b0df646.png)

In this example, he exposed port 3140 for Preview.js after clicking on:
![image](https://user-images.githubusercontent.com/87228994/219602144-2a145049-3f49-4890-a8bd-75352324dcf5.png)

But if I open it, it shows me only 
![image](https://user-images.githubusercontent.com/87228994/219602017-562274bd-a751-42a3-ac3b-99b58a77c7e0.png)

### Reproduction

1. Open any repo with Gitpod
https://gitpod.io/#<Repo URL>
e.g. https://gitpod.io/#https://github.com/mmailaender/Portfolio/tree/main
3. Install Preview.js
4. Try to open a component in Preview.js

### Preview.js version

v1.17.3

### Framework

Nextjs 13

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 30.33 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  IDEs:
    Emacs: 26.3 - /usr/bin/emacs
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.75.1 - /ide/bin/remote-cli/code
    Vim: 8.1 - /usr/bin/vim
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hey @mmailaender, sorry Gitpod isn't supported at the moment.

**Comment by mmailaender** [comment]
@fwouts have you plans to support it in the near future, or are you supporting any other cloud IDE?

**Comment by fwouts** [comment]
Not in the near future unfortunately. I'd love to have it work, but the top priority for the moment is making Preview.js profitable, or I will unfortunately have no more time to allocate to it!
