### ISSUE TITLE
No component was found on offset ...

### ISSUE THREAD

**Issue by NathanKr** [fwouts/previewjs#138]
### Describe the bug

I am getting an error 'No component was found on offset 0' when I try to see the component preview

### Reproduction

Open vs code for https://github.com/NathanKr/react-draw-events
Navigate to https://github.com/NathanKr/react-draw-events/blob/main/src/components/Events.jsx 
Put the cursor on the first char on the file
Click the icon 'Open preview' or 'Open react preview'
see the error No component was found on offset 0

### Preview.js version

v1.0.3

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 1.72 GB / 7.89 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.64.0 - C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.31624.102 (Visual Studio Community 2019)
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

npm

### Anything else?

![error](https://user-images.githubusercontent.com/12426564/152676257-6de71ab5-3e9a-4324-a85f-43197f7abc96.png)

**Comment by fwouts** [comment]
Thank you so much for sharing your repo, that'll make it easy to fix :)

It looks like components aren't being detected in your project. As a temporary workaround, you can install `@types/react` as an additional dependency to your project, but of course that shouldn't be necessary for Preview.js to work. I'll try and get that fixed soon :)

In addition, that top-right button does seem broken. It's on the list to be fixed for next release.

**Comment by fwouts** [comment]
Hi @NathanKr, I've just published Preview.js v1.0.4 which should make Preview.js work with your project out of the box now.

The top-right button should also work too, although you'll need to position the cursor within the definition of a React component (not the beginning of the file).

Let me know how you go :)
