### ISSUE TITLE
Cannot inspect object properties in console

### ISSUE THREAD

**Issue by wststone** [fwouts/previewjs#14]
I am building a drawing component with canvas and i was attempting to log mouse positions stored in an array, it would be great if we could inspect the properties in those objects, also I have to manually import the root css file to make tailwindcss work in the component.
![react-preview-console-issue](https://user-images.githubusercontent.com/42225395/123354417-2eaf8e80-d596-11eb-8ae8-77edff385a18.png)

**Comment by fwouts** [comment]
Thanks for the report! I'm actually surprised that this works at all 😆

The CSS import issue sounds related to https://github.com/zenclabs/reactpreview/issues/10#issuecomment-868047256. You should be able to solve that with the `Wrapper.tsx` solution explained there.

Being able to inspect object properties sounds very useful. Adding to the list 👍

**Comment by fwouts** [comment]
Fix is merged for Preview.js—will hopefully be released early next week.
