### ISSUE TITLE
The requested module '..' does not provide an export named 'IStyle'

### ISSUE THREAD

**Issue by roggenbrot** [fwouts/previewjs#143]
### Describe the bug

When trying to open an preview of an react component that uses [fluent ui controls](https://developer.microsoft.com/en-us/fluentui#/controls/web) an syntax error is thrown, complaining about a interface that is used by the component which should be previewed, but not exported by fluent ui:

![grafik](https://user-images.githubusercontent.com/41467575/152949736-5ca19217-2088-4537-9f06-126b1f4244b5.png)

Import:

```
import {
  IPivotStyleProps,
  IPivotStyles,
  IStyle,
  IStyleFunctionOrObject,
  ITheme,
} from "@fluentui/react";
```

Same error does not occur during webpack compilation.

Did I miss a configuration option? 

### Reproduction

1. Open preview via "Open ... in Preview.js"

### Preview.js version

v1.0.4

### System Info

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 6.72 GB / 15.42 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.3.0 - /usr/bin/node
    Yarn: 3.1.1 - /usr/bin/yarn
    npm: 8.4.1 - /usr/bin/npm
  IDEs:
    Nano: 6.0 - /usr/bin/nano
    VSCode: 1.64.0 - /usr/bin/code
  Browsers:
    Chromium: 98.0.4758.80
    Firefox: 96.0.3
```

### Used Package Manager

yarn

### Extension logs (useful for crashes)

```shell
No error
```

### Preview logs (useful for rendering errors)

When opening the preview in browser another error is shown:

```
import not found: ITheme 
```

console contains the following error message:

```shell
SyntaxError: import not found: IContextualMenuItem logs.ts:11:16
```

Both, ITheme and IContextualMenuItem are fluent ui interfaces

### Anything else?

![grafik](https://user-images.githubusercontent.com/41467575/152952097-c62389ef-8396-4196-9029-fc887b4b7027.png)

**Comment by fwouts** [comment]
Hi @roggenbrot, thanks for filing this bug.

This looks to be an edge case that I've overlooked. In the meantime you should be able to fix it by using `import type` instead of `import`.

Could you let me know if that works?

**Comment by roggenbrot** [comment]
Thx for the quick response and help. Indeed `import type` seems to resolve the issue.

Can you maybe point me to the location where the problem occurs so that I could create a PR. (Fixing this issue on my own seems to be less effort then refactoring 1000 files :) )

**Comment by fwouts** [comment]
I'm not entirely sure that it's fixable unfortunately!

I should also warn you before you go through the effort of creating a PR that I plan to dual-license this project in order to distribute a not-quite-open source "Pro" version (under BSL license), so I will need to require all contributors to sign a copyright assignment clause to make that possible (I haven't yet had time to set that up or to write a Contributing guide).

In order to find the places to update your code, the simplest is to set "isolatedModules" to true in your tsconfig.json. Hopefully it's less than 1000 files?

**Comment by roggenbrot** [comment]
> In order to find the places to update your code, the simplest is to set "isolatedModules" to true in your tsconfig.json.

We already use isolatedModules (Without any problems/findings so far)


It seems to be a fluentui problem.


For all that are running into this problem:


Microsoft has released a converter to transform all interface imports of fluentui 

https://www.npmjs.com/package/transform-typed-imports
