### ISSUE TITLE
Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>     at useLeafletContext

### ISSUE THREAD

**Issue by baditaflorin** [fwouts/previewjs#1565]
### Describe the bug

I know I can manually create a <MapContainer> for each component, but I am curious if I could do this using a Wrapper component?

### Reproduction

Create a react-leaflet map component
Create a child component that needs a <MapContainer>, that will get from the parent component. But during debugging, it is useful to be able to see inside preview.js the <MapContainer> 

### Preview.js version

Latest

### Framework

React 18

### System Info

```shell
MacOsX
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Let me know if anything is missing from https://previewjs.com/docs/config/wrapper to make it clearer.
