### ISSUE TITLE
Unable to trigger preview.js in Vue Vite project with Storybook

### ISSUE THREAD

**Issue by MingNeo** [fwouts/previewjs#1591]
### Describe the bug

 I’m using Storybook in my Vue Vite project and I’m having trouble triggering preview.js. I get the following message: “Creating Preview.js workspace (plugin: @previewjs/plugin-react) at xxx”. I’m wondering if this is because Storybook is introducing React dependencies and causing an error in judgment.

### Reproduction

Install Storybook and initialize it.
Reload VSCode.

### Preview.js version

1.21.1

### Framework

vue3

### System Info

```shell
MacOsX
```

### Used Package Manager

pnpm

### Preview logs (useful for rendering errors)

```shell
[ready] Preview.js daemon server is now running at http://localhost:9315
Creating Preview.js workspace (plugin: @previewjs/plugin-react) at /Users/klose/code/admin-demo
```

**Comment by fwouts** [comment]
Hi @MingNeo, that is definitely the reason. If you upgrade to Storybook 7, you shouldn't need React as a dependency anymore.

**Comment by fwouts** [comment]
This should be fixed in the next version, which I'm hoping to release today/tomorrow.

**Comment by fwouts** [comment]
I've just pushed out the release (v1.22.0), it should be live in an hour or so.

**Comment by fwouts** [comment]
Hey @MingNeo, just checking if you had a chance to try out the update, which should fix this? Thanks!

**Comment by MingNeo** [comment]
wow! Problem solved, it's working great! thank you for the fix!
