### ISSUE TITLE
Lose focus / resets state after ~5seconds

### ISSUE THREAD

**Issue by cschroeter** [fwouts/previewjs#1612]
### Describe the bug

Some sort of interval (~5seconds) in the background reset the preview (see video)

https://user-images.githubusercontent.com/1846056/234788897-a9a53fb2-7a6f-4a38-bf19-b3938f1b84ae.mov

### Reproduction

1. create-next-app
2. open project with vscode
3. create demo component

```tsx
export const Demo = () => {
  return <input />;
};
```
4. run preview.js

### Preview.js version

v1.22.2

### Framework

React, Next

### System Info

```shell
Mac
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Thanks for the bug report and the clear example!

Will look into it. Expect a fix within the week.

**Comment by fwouts** [comment]
Hey @cschroeter, the fix is being released in v1.22.3 which should be live soon.

Thanks again for reporting the issue!

**Comment by cschroeter** [comment]
@fwouts happy to say  that the issue is solved <3

**Comment by fwouts** [comment]
Yay! Keep reporting other issues you run into!
