### ISSUE TITLE
Unable to see PreviewJs icon in Webstorm

### ISSUE THREAD

**Issue by alveshelio** [fwouts/previewjs#1624]
### Describe the bug

Here's the info about Webstorm:

WebStorm 2023.1
Build #WS-231.8109.174, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=848bbd
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=848bbd
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    com.github.patou.gitmoji (1.12.1)
    indent-rainbow.indent-rainbow (2.1.0)
    com.jetbrains.plugins.ini4idea (231.8109.217)
    com.github.lppedd.idea-conventional-commit (0.22.0)
    awesome.console (0.1337.12)
    gr.jchrist.gitextender (0.7.0)
    zielu.gittoolbox (500.0.6+213)
    com.mallowigi (90.0.0)
    com.github.copilot (1.2.5.2555-nightly)
    com.nasller.CodeGlancePro (1.6.2)
    com.previewjs.intellij.plugin (1.22.3)
    com.paperetto.dash (3.3)
    com.intellij.properties (231.8109.91)
    com.wix.scss.lint (2.1.1)
    com.godwin.json.parser (1.4.1)
    quokka.js (1.0.379)
    in.twbs.pure (0.0.1)
    ru.adelf.idea.dotenv (2023.1)
    XPathView (231.8109.91)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-231)
    org.asciidoctor.intellij.asciidoc (0.38.13)
    org.jetbrains.plugins.astro (231.8109.91)
    com.chrisrm.idea.MaterialThemeUI (8.6.3)
    com.intellij.lang.jsgraphql (4.0.0)
    izhangzhihao.rainbow.brackets (2023.2.7)

I'm using the new Webstorm UI
![image](https://user-images.githubusercontent.com/8176422/235461803-2311033f-48f8-4943-92f7-63eda40eb0e5.png)

### Reproduction

There's no reproduction steps. Simply open Webstorm with the new UI and you'll see that the icon is missing.

### Preview.js version

v1.22.3

### Framework

React 17

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 719.19 MB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh

Binaries:
    Node: 16.16.0 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 9.6.4 - ~/n/bin/npm
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Thanks for the report @alveshelio!

I can confirm the "Preview.js logs" tab is missing in the new UI, but I had assumed it was just hidden by default, as a design choice by Jetbrains to make the UI simpler. I haven't yet checked if there's a way to force it to be visible.

In my case, the "Open in Preview.js" link above each component still appears and Preview.js continues to function despite the missing logs tab.

If that's not the case, could you try switching back to the classic UI and seeing if there's any error in the Preview.js logs?

**Comment by fwouts** [comment]
I figured out how to show the logs, you need to click the "..." on the left side of the screen. Does that work for you?

<img width="1440" alt="Screenshot 2023-05-03 at 9 12 26 am" src="https://user-images.githubusercontent.com/772570/235804700-4ab4eba8-f429-4985-8fa3-c14b8c787512.png">

**Comment by alveshelio** [comment]
Hi @fwouts,

I've just upgraded PreviewJs to 1.22.4.

Unfortunately I still don't see it anywhere 😞 

This is what I have 
![image](https://user-images.githubusercontent.com/8176422/235911946-31a225a6-5963-4cef-8f07-975446fb10c7.png)

Whenever I click on one of the items in this submenu then they are added to the sidebar on the right. And in the right sidebar, whenever I "Hide" an item, it will appear back in the submenu on the left.

Bellow are some other submenus and none of them show anything related with PreviewJs
![image](https://user-images.githubusercontent.com/8176422/235911992-a50d4ab8-30fc-4a0b-aa97-0b8d753320a6.png)

![image](https://user-images.githubusercontent.com/8176422/235912039-4c3363d2-8b85-431e-b23f-4b54fbf8ac9a.png)

This is my sidebar:
![image](https://user-images.githubusercontent.com/8176422/235912424-23d4f7ae-25c6-4f50-8002-a5a8fc42a542.png)

**Comment by fwouts** [comment]
@alveshelio could you try installing https://s3.previewjs.com/previewjs-1.22.4-helioalves.0.zip and telling me if it works? Note you'll still need to open at least one file.

**Comment by alveshelio** [comment]
So Installing the new Preview.js version didn't helped. The reason is that in Webstorm, we can disable `Inlay Hints` and because I had `
