### ISSUE TITLE
No compatible workspace detected with SvelteKit 1.22.4

### ISSUE THREAD

**Issue by esbeto** [fwouts/previewjs#1884]
### Describe the bug

I was creating a new SvelteKit project and wanted to use my favorite development tool Preview.js. But I was unable to use the extension in VSCode.

### Reproduction

Create a new SvelteKit project

```
pnpx create-svelte@latest my-app
cd my-app
pnpm install
```

Open VS Code
```
code .
```

Try to start Preview.js server

Error appears

### Preview.js version

v1.24.2

### Framework

Svelte 4.1.2

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 422.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/Library/Caches/fnm_multishells/85694_1690999208721/bin/node
    npm: 9.7.2 - ~/Library/Caches/fnm_multishells/85694_1690999208721/bin/npm
    pnpm: 8.6.11 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.80.2 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Brave Browser: 89.1.21.76
    Chrome: 115.0.5790.114
    Edge: 115.0.1901.188
    Safari: 16.5.2
```

### Used Package Manager

pnpm

**Comment by fwouts** [comment]
Thanks for the report. Preview.js doesn't yet support Svelte 4, I'll try and fix that soon!

**Comment by fwouts** [comment]
Hey @esbeto, a fix is in the works in https://github.com/fwouts/previewjs/pull/1761 but it might take a little while to land as there are quite a few refactors going into the upcoming release.

In the meantime, if you want to just get it to work, you can change line 272 at `~/.vscode/extensions/zenclabs.previewjs-1.24.2/dist/node_modules/@previewjs/plugin-svelte/dist/index.mjs`:
```diff
- return parseInt(version) === 3;
+ return parseInt(version) >= 3;
```

**Comment by fwouts** [comment]
Hi @esbeto, could you try the new version of the VS Code extension (v1.24.4) and let me know if it started working now?

**Comment by esbeto** [comment]
It's working now, thanks!
