### ISSUE TITLE
No component was found at offset (no.)

### ISSUE THREAD

**Issue by Al-Sharqawy25** [fwouts/previewjs#1921]
### Describe the bug

The extension does not run as it displays the following error over and over again "no component was fount at offset (variable number)"

### Reproduction

1. ctrl + shift + p to run the extension
2. error displayed "no component was found at offset ..."

### Preview.js version

v1.24.2

### Framework

React 18.2.0

### System Info

```shell
IDEs
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Please provide more information about your project @Al-Sharqawy25. Ideally a minimal repro would be best.

**Comment by fwouts** [comment]
Closing as there isn't enough information to reproduce this issue.
