### ISSUE TITLE
something goes wrong with my project

### ISSUE THREAD

**Issue by xwbxxx** [fwouts/previewjs#1928]
### Describe the bug

I can't preview my react project and here illustrate the log and error reporting:
![image](https://github.com/fwouts/previewjs/assets/49603007/1c899d30-74d0-48a8-abd0-2db3241a8951)
I suspect that there is a problem with one of the components in this project, because this project is two years old, and my newly created project works fine on my computer and ide with preview.js.

### Reproduction

1. start pycharm and open my project
2. after a few seconds initializing, my IDE raised a fatal error
![image](https://github.com/fwouts/previewjs/assets/49603007/458b8d13-7af5-4d63-86cd-140160863474)

### Preview.js version

V1.20.1

### Framework

react 16.13.1

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.26 GB / 13.86 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Ides:
    Pycharm 2021.3.3 professional version
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

npm

### Preview.js logs (check bottom panel in IntelliJ)

```shell
[ready] Preview.js daemon server is now running at http://localhost:2481
No compatible Preview.js plugin for workspace: C:\Users\13327\PycharmProjects\ZJU_SummerSchool
```

### Anything else?

Here are all the dependencies of this project in package.json: 
"dependencies": {
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@uiw/react-baidu-map": "^1.17.1",
    "clsx": "^1.1.1",
    "echarts": "^4.8.0",
    "echarts-for-react": "^2.0.16",
    "papaparse": "^5.2.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },

**Comment by fwouts** [comment]
Hi @xwbxxx, it looks like you're using an unsupported version of Preview.js. Unfortunately newer versions are only compatible with PyCharm 2022.3+ (JetBrains keep making breaking changes to their own SDK, which makes it very difficult to release a plugin that works with both new and older versions).

As an alternative, you may want to try the CLI: https://previewjs.com/docs/platforms/cli
