### ISSUE TITLE
React Preview resulted in an error

### ISSUE THREAD

**Issue by SitoNumbis** [fwouts/previewjs#221]
### Describe the bug

Command "React Preview: Open React Preview" resulted in an error (Language cliente is not ready yet)

### Reproduction

1 -  View
2 - Command Palette
3 - React Preview: Open React Preview

### Preview.js version

0.7.1 beta

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.67 GB / 15.65 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.64.2 - C:\Users\Inmersoft\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.55)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

yarn

### Anything else?

![image](https://user-images.githubusercontent.com/40501794/154687253-e18804f9-f1d9-4dfa-965e-bd03ca874507.png)

**Comment by fwouts** [comment]
Hi @SitoNumbis, would you be able to try previewjs.com instead? This will soon replace React Preview, and it should have fewer bugs :)
