### ISSUE TITLE
Multiple inlay hints

### ISSUE THREAD

**Issue by smeevil** [fwouts/previewjs#2428]
### Describe the bug

Hi,

I'm using Intellij 2023.3.3 and PreviewJs 1.27.4.
It shows multiple inlay hints for Open <component> in Preview.js

Is there something I misconfigured or is this a bug?

![CleanShot 2024-01-29 at 19 40 17@2x](https://github.com/fwouts/previewjs/assets/13874/1c92d25e-b115-4b1d-9139-ff8e27e3e651)

### Reproduction

open a .tsx component

### Preview.js version

v1.27.4

### Framework

Bun 1.0.13 / Vite 5.0.8 / React 18.2.0

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 10.89 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    bun: 1.0.13 - ~/.bun/bin/bun
    Watchman: 2023.11.13.00 - /opt/homebrew/bin/watchman
  IDEs:
    IntelliJ: 2023.3.3
    Vim: 9.0 - /opt/homebrew/bin/vim
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Browsers:
    Safari: 17.2.1
```

### Used Package Manager

npm

### Preview.js logs (check bottom panel in IntelliJ)

```shell
[ready] Preview.js daemon server is now running at http://localhost:60529
[19:38:48.812] INFO (11379): Created Preview.js workspace (plugin: @previewjs/plugin-react) at /Users/smeevil/dev/private/***/
[19:38:48.815] INFO (11379): Preview.js server running at http://localhost:3140.
[19:38:50.330] WARN (11379): Unable to recognise type with flags 64 in bigint
```

**Comment by fwouts** [comment]
Hi @smeevil, there's currently a bug in IntelliJ because they decided to break the API used to show those inlays. More details in https://youtrack.jetbrains.com/issue/IDEA-333164.

I'm currently trying to implement the workaround they mentioned in the last comments, hopefully will be out in the next few days.

**Comment by fwouts** [comment]
This should be solved by https://github.com/fwouts/previewjs/commit/0d24f62e1933cb7df71cdbf336551498864f4d32, it will be released in v1.28.0 once approved by JetBrains (hopefully tomorrow).

**Comment by smeevil** [comment]
Awesome, thanks for the quick action!

**Comment by fwouts** [comment]
No worries! Also FYI you'll need IntelliJ 2023.3 to get the fix (it uses an API that isn't available in earlier versions).
