### ISSUE TITLE
Redundant lines of "Open App in Preview.js"

### ISSUE THREAD

**Issue by danny-su** [fwouts/previewjs#2440]
### Describe the bug

<img width="366" alt="image" src="https://github.com/fwouts/previewjs/assets/12178855/e3889973-9c43-43d1-9059-7400738403e9">

### Reproduction

N/A

### Preview.js version

<img width="289" alt="image" src="https://github.com/fwouts/previewjs/assets/12178855/274c6f98-3422-4f64-8b58-1fb3057a9dd7">

### Framework

18.2.0

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 15.24 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    Yarn: 4.1.0 - /opt/homebrew/bin/yarn
    npm: 10.4.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - /opt/homebrew/bin/bun
  IDEs:
    Emacs: 29.2 - /opt/homebrew/bin/emacs
    IntelliJ: 2023.3.3
    PhpStorm: 2023.3.3
    Sublime Text: 4169 - /opt/homebrew/bin/subl
    VSCode: 1.86.0 - /opt/homebrew/bin/code
    Vim: 9.1 - /opt/homebrew/bin/vim
    WebStorm: 2023.3.3
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Browsers:
    Brave Browser: 121.1.62.156
    Chrome: 121.0.6167.139
    Edge: 121.0.2277.98
    Safari: 17.3
    Safari Technology Preview: 17.4
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hi @danny-su, the fix for this was merged yesterday and is awaiting approval by JetBrains. Make sure you're using IntelliJ 2023.3 and you should get the update soon 😊

**Comment by fwouts** [comment]
v1.28.0 is now available with the fix, let me know how you go!

**Comment by danny-su** [comment]
@fwouts Thanks, It was fixed.

**Comment by danny-su** [comment]
<img width="1068" alt="image" src="https://github.com/fwouts/previewjs/assets/12178855/b3e97f0d-7ab6-4921-b47f-94c6aca780e0">

@fwouts "(eval):1: can't change option: zle"

**Comment by fwouts** [comment]
That should be a benign warning. Are you seeing any issues as a result of that?

**Comment by danny-su** [comment]
@fwouts No
