### ISSUE TITLE
no button in vscode

### ISSUE THREAD

**Issue by mingmingshiliyu** [fwouts/previewjs#2737]
### Describe the bug

![1723563362212](https://github.com/user-attachments/assets/7abbdbe4-29ef-4004-92b8-5c7660b050ec)
![1723563437500](https://github.com/user-attachments/assets/ba9fad95-3831-47e3-9771-dd4a5d890380)
![1723563476387](https://github.com/user-attachments/assets/814973ed-c23d-4adf-8d8e-0d916e69686c)

### Reproduction

vscode,preview.js

### Preview.js CLI version

latest

### Framework

  "react": "^18.3.1",

### System Info

```shell
win11
```

### Used Package Manager

npm

**Comment by mingmingshiliyu** [comment]
![1723738266933](https://github.com/user-attachments/assets/2595247f-b971-4d59-b7bd-69684b9493dc)

**Comment by mingmingshiliyu** [comment]
same error:   https://github.com/fwouts/previewjs/issues/1921

**Comment by fwouts** [comment]
Closing as no repo was provided.
