### ISSUE TITLE
ADD ability to disable Preview.js per (IDEA) project

### ISSUE THREAD

**Issue by allanlaal** [fwouts/previewjs#294]
currently its running automatically in PHP projects

**Comment by fwouts** [comment]
Good idea! I wonder how that can be detected. I'll see if it's possible to delay startup until you open a compatible file.

**Comment by allanlaal** [comment]
IDEA itself hasn't added it in 14 years: https://youtrack.jetbrains.com/issue/IDEA-230227

heres an IntelliJ IDE plugin that has the option to enable it per project:

https://github.com/magento/magento2-phpstorm-plugin/search?q=Enable+Magento+integration

**Comment by fwouts** [comment]
Hi @allanlaal, since v1.5.0, the Preview.js plugin for IntelliJ will not do anything unless you're opening a specific file type that's relevant to is such as `.js`. I believe that's as good as I can do with the current IntelliJ SDK!
