### ISSUE TITLE
Release the CLI version of PreviewJS?

### ISSUE THREAD

**Issue by alexkreidler** [fwouts/previewjs#303]
I really loved using the React Preview CLI, and I'd like to try out PreviewJS. I don't want to install a VSCode extension because I like using my browser (Firefox) with DevTools and the React and Redux DevTools and some other extensions.

I would love it if you could release the CLI on NPM so I could run a quick `npm i -g @previewjs/cli` install command to try it out.

**Describe alternatives you've considered**
I could clone the repository, install the dependencies, build the code, and try it out.

Thanks!

**Comment by fwouts** [comment]
Hi @alexkreidler, thanks for the suggestion!

I've seen very little uptake of the CLI version (49 weekly downloads!) so it's not something I've been prioritising for Preview.js.

The main blocker at this point is that the CLI requires a component finder to be useful (the side panel in React Preview), and I haven't yet built it for Preview.js, although it's halfway there. The current plan is to make it part of Preview.js Pro, which will likely cost $10/month or $100/year to support development of Preview.js.

Would you be willing to pay for a Pro license to get this feature?

**Comment by fwouts** [comment]
Hi @alexkreidler, just a quick update, the CLI is planned hopefully in a few weeks :)
