### ISSUE TITLE
Can't preview Vue components

### ISSUE THREAD

**Issue by bvqbao** [fwouts/previewjs#407]
### Describe the bug

I don't know why but I can't preview any component in my vue project setup, even a "HelloWorld" component. Not sure if this is a bug or I'm missing something.

![image](https://user-images.githubusercontent.com/4357219/161252229-5eb5e05f-842c-4f2a-86d4-23939d70114b.png)

### Reproduction

1. Go to a SFC file.
2. Click Open <ComponentName> in Preview.js

### Preview.js version

v1.5.1

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.81 GB / 15.80 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.66.0 - C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.1.32228.430 (Visual Studio Community 2022)
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
[2022-04-01 18:04:44.945] [exthost] [info] ExtensionService#_doActivateExtension zenclabs.previewjs, startup: false, activationEvent: 'onLanguage:javascript'
```

### Anything else?

[vite.config.js.txt](https://github.com/fwouts/previewjs/files/8397078/vite.config.js.txt)
[package.json.txt](https://github.com/fwouts/previewjs/files/8397079/package.json.txt)

**Comment by fwouts** [comment]
Thanks a ton for filing this issue @bvqbao!

It looks like the iframe where the preview is meant to appear is somehow broken for you.

Do you see any error in the webview logs? (`Ctrl+P` then `Developer: Open Webview Developer Tools`)

**Comment by bvqbao** [comment]
Here is the log file in question
[vscode-app-1648814785758.log](https://github.com/fwouts/previewjs/files/8397552/vscode-app-1648814785758.log)
.

**Comment by fwouts** [comment]
Awesome I think this will help narrow it down, thanks so much!

**Comment by bvqbao** [comment]
Ok. This is a weird bug.

1. Create a new vue project with ```npm init vue@3```
I can preview components in this new project:
![image-20220402145713364](https://user-images.githubusercontent.com/4357219/161374013-a5a09569-9ca2-429e-b0eb-2bd87593c9e4.png)

2. Copy the src folder (attached) from my actual project to this new project. The previews still work:
![image-20220402145904747](https://user-images.githubusercontent.com/4357219/161374090-1fa2e7a9-555b-4bbf-9233-3c2902d8f11a.png)

3. Copy the dependencies section in package.json from my actual project to the new project. And the previews stop working:
![image](https://user-images.githubusercontent.com/4357219/161374414-0db90dfd-dfb8-4c2b-b74c-c9fb0db08392.png)

Sometime, I just open the package.json file and the previews stop working (don't need to copy the dependencies section). Other times, the previews work after step 3 for awhile and then suddenly stop working.

Attachments:
[src.zip](https://github.com/fwouts/previewjs/files/8402122/src.zip)

**Comment by fwouts** [comment]
Thanks, this is really helpful.

Just to double check, did you run `npm install` or `yarn install` after updating package.json?

**Comment by bvqbao** [comment]
yes. I did run ```npm install``` before previewing.

**Comment by fwouts** [comment]
OK, that's unfortunate!

I plan to release a CLI version of Preview.js in the next few weeks, which should hopefully make this easier to debug. Let's reconvene then :)

**Comment by fwouts** [comment]
Closing this issue as no further information was provided in the last year.
