### ISSUE TITLE
Autogenerated props don't use default values

### ISSUE THREAD

**Issue by beforan** [fwouts/previewjs#438]
## Problem
When I specify default prop values for a component, it'd be nice if when previewed the default values were used in the autogenerated props, since often they're a reasonable starting point for whatever I'm testing, and I can go ahead and change only the props I'm interested in, rather than either having to change them all, or setup custom previews.

Currently I'm defining defaults as follows in Typescript:

```ts
// Contrived example

interface BoxProps extends ComponentPropsWithoutRef<"div"> {
  bgColor: string
}

const Box = ({ bgColor = "red" }: BoxProps) => (
  <div
    style={{ width: "100px", height: "100px", backgroundColor: bgColor }}
  />
);
```

and Preview.js autogenerates the following when previewing:
```js
properties = {
  bgColor: "bgColor",
};
```

## Solution
Preview.js adopts any defined default values for props where possible.

In my contrived example above, it would be ideal if Preview.js autogenerated the following:

```js
properties = {
  bgColor: "red",
};
```

## Alternatives
Adding custom previews to every component to set the defaults purely for Preview.js. But this is duplicating my already defined defaults; I'd rather use this functionality for additional alternative preview presets when that's desirable.

**Comment by fwouts** [comment]
Hi @beforan. Thanks for taking the time to file an issue!

That sounds perfectly reasonable, I'll see if it's possible.

For now, you might also be able to make the property itself optional in your props type definition? In that case Preview.js will omit it.

**Comment by fwouts** [comment]
This will be live soon in VS Code and JetBrains, v1.6.4. It's also live in `@previewjs/cli` v1.0.5.

Let me know how you go! :)

**Comment by fwouts** [comment]
Closing this as fixed, feel free to reopen if you run into this again!
