### ISSUE TITLE
Add support for `vite-plugin-svg-icons`

### ISSUE THREAD

**Issue by smeevil** [fwouts/previewjs#442]
**Is your feature request related to a problem? Please describe.**
When using the `vite-plugin-svg-icons` the preview.js server throws an error like:

```
The following dependencies are imported but could not be resolved:

  virtual:svg-icons-register (imported by <...snip...>/src/index.tsx)

Are they installed?
```

**Describe the solution you'd like**

Be able to use the `preview.config.js` vite config option to extent the default config to configure custom plugins

**Describe alternatives you've considered**
I tried to add the following to the `vite` entry in the `preview.config.js`

```
plugins: [
      createSvgIconsPlugin({
        iconDirs: [svgPath],
        symbolId: 'icon-[name]',
      }),
      svgrPlugin({
        svgrOptions: {
          icon: true,
        },
      }),
    ],
```

but this resulted in the following errors: 
```
4:06:48 PM [vite] Internal server error: Transform failed with 2 errors:
<...snip...>/src/Components/Icon/svg/palette.svg:6:12: ERROR: The symbol "React" has already been declared
<...snip...>/src/Components/Icon/svg/palette.svg:7:9: ERROR: The symbol "ReactComponent" has already been declared
  Plugin: vite:svgr
  File <...snip...>/src/Components/Icon/svg/palette.svg
  
  The symbol "React" has already been declared
  4  |  
  5  |  export { ReactComponent };
  6  |  import * as React from "react";
     |              ^
  7  |  function ReactComponent(props) {
  8  |    return /* @__PURE__ */ React.createElement("svg", {
  
  The symbol "ReactComponent" has already been declared
  5  |  export { ReactComponent };
  6  |  import * as React from "react";
  7  |  function ReactComponent(props) {
     |           ^
  8  |    return /* @__PURE__ */ React.createElement("svg", {
  9  |      xmlns: "http://www.w3.org/2000/svg",
  
      at failureErrorWithLog (<...snip...>/node_modules/esbuild/lib/main.js:1600:15)
      at <...snip...>/node_modules/esbuild/lib/main.js:1389:29
      at <...snip...>/node_modules/esbuild/lib/main.js:663:9
      at handleIncomingPacket (<...snip...>/node_modules/esbuild/lib/main.js:760:9)
      at Socket.readFromStdout (<...snip...>/node_modules/esbuild/lib/main.js:629:7)
      at Socket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9)
      at Socket.Readable.push (internal/streams/readable.js:204:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by fwouts** [comment]
Hi @smeevil, thanks for reporting this!

Preview.js already includes an SVGR plugin, could you try adding only the first one?

**Comment by smeevil** [comment]
Hi @fwouts,

Only including the svg-icons-plugin results in the following console error:

```
SyntaxError: The requested module '/preview/src/Components/Icon/svg/language.svg?import' does not provide an export named 'ReactComponent'
```

**Comment by fwouts** [comment]
Thanks for sharing, I thought it would work since it normally would export `ReactComponent` (see https://previewjs.com/docs/config/svgr).

I'll add an option to disable the embedded SVGR plugin so that you can use your own version, give me a couple of days :)

**Comment by smeevil** [comment]
awesome! take you're time :)

**Comment by fwouts** [comment]
@smeevil you should now be able to upgrade to `@previewjs/plugin-react` v3.0.1 and use the following `preview.config.js`:
```
const { reactFrameworkPlugin } = require("@previewjs/plugin-react");

/** @type {import("@previewjs/config").PreviewConfig} */
module.exports = {
  frameworkPlugin: reactFrameworkPlugin.create({
    svgr: {
      disable: true,
    },
  }),
  vite: ... // add both of your plugins here as you did before
};

```

**Comment by smeevil** [comment]
@fwouts This works perfectly :)
I've enabled the trial for the pro version and it shows all the components without a problem except for.... storybook components. This seem to generate a small error. I've attached a screenshot and am not sure if this is from preview.js or somewhere deeper in the stack. I _think_ it might be from preview.js as storybook by itself works fine (with the same component preview)
![CleanShot 2022-04-13 at 13 42 59](https://user-images.githubusercontent.com/13874/163173108-e171ad1e-60d5-4ed1-9680-78491faac1e7.png)

**Comment by fwouts** [comment]
Glad to hear you got one step further :)

I haven't seen that error before—I suspect it's one of your Storybook dependencies that's not playing nice with [Vite](https://vitejs.dev), which Preview.js is based on.

Any chance you'd be able to share a minimal repro, or maybe start with the list of imports in that storybook file?

There might also be some errors logged in the Preview.js output panel (VS Code) or Preview.js logs bottom panel (IntelliJ/WebStorm).

I'm also about to release a CLI version which should hopefully make this a bit easier to debug...

**Comment by smeevil** [comment]
Hi @fwouts,

It was a assumption on my side that caused the error.
I thought it would pick up the config defined in storybook but it uses it's own preview.config.js for storybook previews as well. After adding the vitePluginMdToHTML to the plugins this is now also working as advertised :)

Thank you so much for your support and looking forward to what the future brings for this plugin!

**Comment by fwouts** [comment]
That's awesome. Wait, are you saying you got Markdown working in Preview.js? 😱

**Comment by fwouts** [comment]
Hi @smeevil, a quick heads-up that in the latest version of Preview.js (1.9.0) you shouldn't need to set `frameworkPlugin` in `preview.config.js` anymore as SVGR is now disabled by default.

You can just do:
```js
/** @type {import("@previewjs/config").PreviewConfig} */
module.exports = {
  vite: ... // your Vite config
};
```

In fact I'm about to remove the `frameworkPlugin` field from the config entirely, as it's not needed for anything anymore.

Let me know if you see any issues with that change!

**Comment by smeevil** [comment]
Awesome!

Currently I use the following config:

```js
const path = require('path')
const { createSvgIconsPlugin } = require('vite-plugin-svg-icons')

const svgPath = path.resolve(process.cwd(), 'src/Components/Icon/svg')

module.exports = {
  wrapper: {
    path: 'src/previewjs.tsx',
    componentName: 'PreviewWrapper',
  },
  alias: {},
  publicDir: 'public',
  vite: {
    envPrefix: 'REACT_APP_',
    plugins: [
      createSvgIconsPlugin({
        iconDirs: [svgPath],
        symbolId: 'icon-[name]',
      }),
    ],
  },
}
```

Together with the preview wrapper: 

```tsx
import './Lib/i18n'
// eslint-disable-next-line import/no-unresolved
import 'virtual:svg-icons-register'

import { ApolloProvider } from '@apollo/client'
import React, { useContext } from 'react'
import { createNetworkStatusNotifier } from 'react-apollo-network-status'
import { BrowserRouter as Router } from 'react-router-dom'

import { authorizedClient } from './Lib/apolloClient'
import { AuthContext, AuthProvider } from './Providers/AuthProvider'

export const PreviewWrapper = ({ children }: { children: JSX.Element }): JSX.Element => {
  const { link } = createNetworkStatusNotifier()
  const { logout } = useContext(AuthContext)

  return (
    <div>
      <ApolloProvider client={authorizedClient(link, logout, 'en')}>
        <AuthProvider>
          <Router>{children}</Router>
        </AuthProvider>
      </ApolloProvider>
    </div>
  )
}

```

The previews work perfectly with translations and the SVG Icon rendering as well :D
