### ISSUE TITLE
Previewjs doesn't find node from wsl

### ISSUE THREAD

**Issue by terebentina** [fwouts/previewjs#457]
### Describe the bug

I have node installed in wsl with volta and Webstorm can find it and use it no problem:
![image](https://user-images.githubusercontent.com/238611/163135030-98842ccd-c54e-4fbb-bfd4-ae2a8917379e.png)
However, Previewjs throws this error:
![image](https://user-images.githubusercontent.com/238611/163135146-0e0b8888-bb00-43fb-82f3-f0242af02dd6.png)

### Reproduction

1. uninstall any node from Windows.
2. install node in wsl
3. previewjs in webstorm can't find node.

### Preview.js version

1.6.0

### System Info

This is from WSL because npx and node only exists there. Windows 10 machine though with Webstorm 2022.1

```
  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 19.60 GB / 24.83 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.2/bin/npm
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.65.2 - /c/Users/dan/AppData/Local/Programs/Microsoft VS Code/bin/code
    Vim: 8.1 - /usr/bin/vim
```

### Used Package Manager

npm

### Preview.js logs (check bottom panel in IntelliJ)

```shell
Please report this issue at https://github.com/fwouts/previewjs/issues java.lang.Error: 'node' is not recognized as an internal or external command, operable program or batch file. at com.previewjs.intellij.plugin.services.PreviewJsSharedService.isInstalled(PreviewJsService.kt:132) at com.previewjs.intellij.plugin.services.PreviewJsSharedService.access$isInstalled(PreviewJsService.kt:33) at com.previewjs.intellij.plugin.services.PreviewJsSharedService$actor$1.invokeSuspend(PreviewJsService.kt:67) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by fwouts** [comment]
Hi @terebentina, thanks for the bug report.

I can confirm that I've never tested WSL, so that's not too surprising.

I imagine installing Node at the Windows level is out of the question?

**Comment by fwouts** [comment]
I suspected so 🙂 I'll look into it! Thanks for bringing it to my attention.

**Comment by fcolomas** [comment]
Is this going to be solved? Have the same problem and confirmed the workaround of installing node in Windows to solve it but I really prefer to have on WSL as my dev box

**Comment by fwouts** [comment]
Hi @terebentina and @fcolomas, would you be able to try the latest version of Preview.js (v1.12)? It should automatically try to run Node from WSL when it's not available in the Windows environment.

**Comment by terebentina** [comment]
I re-enabled previewjs and I can see its daemon starting but I don't get the "Open in Preview.js" link.
![image](https://user-images.githubusercontent.com/238611/184826230-d7371ddc-dfe6-49c0-b757-b7d89c5845e0.png)

**Comment by fwouts** [comment]
Thank you for checking!

May I confirm does Preview.js work with your project if you run it from the CLI with `npx @previewjs/cli` (from WSL)?

**Comment by fwouts** [comment]
Hi @terebentina, just letting you know I shipped an additional fix in v1.12.1 that might help.

Do let me know if the CLI works otherwise, that'll help narrow down the issue :)

**Comment by terebentina** [comment]
CLI works.
I'm on 1.12.2 now and still can't see any way to show the preview inside the ide. The bottom bar shows that Preview.js has started.
On a different note it would be good if you added support for `jsconfig.json` too. It's the same format as `tsconfig.json` but for projects not using TS. In my case the alias wasn't resolved, I renamed the former to the latter and Preview.js stopped complaining about missing paths.

**Comment by fwouts** [comment]
Thanks for trying again @terebentina!

Would you mind sharing more info about your WSL setup? In particular:
- which version of WSL are you using?
- which Linux distro?
- what is your default shell (inside WSL)?
- is your C:\ drive mounted at /mnt/c/ or some other path?

I'll see if I can add some debug logging in the next version :)

**Comment by terebentina** [comment]
- wsl 2
- Ubuntu-20.04
- zsh with oh-my-zsh
- mounted at `/c` instead of the default `/mnt/c`
-

**Comment by fwouts** [comment]
> * wsl 2
> 
>     * Ubuntu-20.04
> 
>     * zsh with oh-my-zsh
> 
>     * mounted at `/c` instead of the default `/mnt/c`

Aha! That would explain it. I had made the assumption that anyone using WSL would use `/mnt/c` as I had no idea that was customisable :)

I wonder how that mapping can be reliably inferred from the environment, otherwise it might require a config file...

**Comment by terebentina** [comment]
Can you read a file from `/etc`? 
The customisations are written to `/etc/wsl.conf` and mine looks like this (note the `root` option):
```
# Automatically mount Windows drive when the distribution is launched
[automount]

# Set to true will automount fixed drives (C:/ or D:/) with DrvFs under the root directory set above. Set to false means drives won't be mounted automatically, but need to be mounted manually or with fstab.
enabled = true

# Sets the directory where fixed drives will be automatically mounted. This example changes the mount location, so your C-drive would be /c, rather than the default /mnt/c.
root = /

# Network host settings that enable the DNS server used by WSL 2. This example changes the hostname, sets generateHosts to false, preventing WSL from the default behavior of auto-generating /etc/hosts, and sets generateResolvConf to false, preventing WSL from auto-generating /etc/resolv.conf, so that you can create your own (ie. nameserver 1.1.1.1).
#[network]
# hostname = DemoHost
#generateHosts = false
#generateResolvConf = false

# Set whether WSL supports interop process like launching Windows apps and adding path variables. Setting these to false will block the launch of Windows processes and block adding $PATH environment variables.
#[interop]
#enabled = true
#appendWindowsPath = false

# Set the user when launching a distribution with WSL.
[user]
default = dan
```

**Comment by fwouts** [comment]
Amazing, thank you! That might be possible although there could be permissions problems perhaps.

Another idea I had was to run `wsl pwd` in the project's directory (from Windows) in the hope that it would automatically do the mapping. Haven't tried it though!

**Comment by fwouts** [comment]
@terebentina Preview.js v1.14 is now available, it addresses your WSL mounting issue (checked with `root = /`) as well as support for jsconfig.json paths (see https://github.com/fwouts/previewjs/issues/962). Let me know how you go!
