### ISSUE TITLE
Less support.

### ISSUE THREAD

**Issue by wingsico** [fwouts/previewjs#470]
### Describe the bug

When I import less file, I got an error: 
> Preprocessor dependency "less" not found. Did you install it?

![Uploading image.png…]()

### Reproduction

1. Create a component
2. Import a less file
3. Open component in Preview.js

### Preview.js version

v1.6.1

### System Info

```shell
System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 51.20 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /var/folders/dw/124jl97955g9js40qyn7s2100000gn/T/fnm_multishells/26759_1649906495175/bin/node
    Yarn: 1.22.17 - /var/folders/dw/124jl97955g9js40qyn7s2100000gn/T/fnm_multishells/26759_1649906495175/bin/yarn
    npm: 6.14.14 - /var/folders/dw/124jl97955g9js40qyn7s2100000gn/T/fnm_multishells/26759_1649906495175/bin/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.66.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    WebStorm: 2021.2.3
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Chrome: 100.0.4896.88
    Edge: 100.0.1185.39
    Safari: 15.4
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hi @wingsico. Just confirming is `less` in your `package.json`?

**Comment by fwouts** [comment]
Closing this as it needs more details, and it's likely installing `less` will fix it. Feel free to re-open if it doesn't!
