### ISSUE TITLE
node_modules/react/package.json?import is outside of Vite serving allow list

### ISSUE THREAD

**Issue by agrublev** [fwouts/previewjs#481]
### Describe the bug

Trying to preview a component inside a monorepo. I get this error:

```
The request url "/Users/me3n/DEVELOPMENT/fcdev/node_modules/react/package.json?import" is outside of Vite serving allow list
```

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/801433/163781759-c423cc56-aca3-444e-aac4-eb950ad15a75.png">

### Reproduction

1. Go to component
2. Click preview

### Preview.js version

v1.6.3

### System Info

```shell
npx: installed 1 in 1.558s

  System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 15.50 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  IDEs:
    Nano: 4.9.2 - /usr/local/bin/nano
    PhpStorm: 2021.2.4
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Browsers:
    Brave Browser: 84.1.12.112
    Chrome: 100.0.4896.88
    Chrome Canary: 96.0.4644.0
    Firefox: 95.0.1
    Safari: 15.2
```

### Used Package Manager

yarn

### Preview.js logs (check bottom panel in IntelliJ)

```shell
Preview.js initialised for project fcdev
Preview.js Server running at http://localhost:3140.
The request url "/Users/me3n/DEVELOPMENT/fcdev/node_modules/react/package.json?import" is outside of Vite serving allow list.

- /Users/me3n/DEVELOPMENT/fcdev/packages/fkit
- /Users/me3n/Library/Application Support/JetBrains/PhpStorm2021.2/plugins/previewjs/controller/dist/installed/node_modules/vite/dist/client

Refer to docs https://vitejs.dev/config/#server-fs-allow for configurations and more details.

The request url "/Users/me3n/DEVELOPMENT/fcdev/node_modules/react/package.json?import" is outside of Vite serving allow list.
```

**Comment by fwouts** [comment]
Hey @agrublev, thanks for reporting this issue!

This is a safety mechanism implemented by [Vite](https://vitejs.dev), which Preview.js is based on.

I'll try to make a new release this week that allows you to override it.

In the meantime, I wonder if it might work if you temporarily add `react` as a dependency in `fcdev/packages/fkit/package.json`?

**Comment by agrublev** [comment]
Sadly it is a dependency, but it is a monorepo.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/801433/163812493-b60cf308-90f4-4ca8-b61d-401d4ce76ca2.png">

**Comment by fwouts** [comment]
Too bad! Out of curiosity, which package manager do you use in this monorepo?

I'm asking because Preview.js itself is also a monorepo (using pnpm) and doesn't appear to suffer from this particular issue!

Workaround coming soon 🙂

**Comment by agrublev** [comment]
We use bolt https://github.com/boltpkg/bolt

**Comment by fwouts** [comment]
Fix is shipped and pending approval from JetBrains (within a day or two hopefully). It will be v1.6.4 :)

**Comment by fwouts** [comment]
I'll close this as fixed, feel free to reopen if you run into any issues!
