### ISSUE TITLE
Styled components with theming 

### ISSUE THREAD

**Issue by mirik999** [fwouts/previewjs#50]
### Describe the bug

using latest nextjs project.
 I have covered my app in ThemeProvider to use global colors and I got an error about theming.
```
Error: Cannot read property 'container' of undefined
TypeError: Cannot read property 'container' of undefined
```

code example
```
const Container = styled.header`
  height: 101px;
  background-color: ${({ theme }) => theme.colors.container};
  filter: drop-shadow(3px 3px 35px rgba(45, 73, 226, 0.071));
  padding: 10px;
`;
```

Types declared in styled.d.ts

* Also react preview doesnt see my style.css file for common styles.

### Reproduction

Unfortunately it is not in github, it is like a simple playground project for myself. I just created nextjs app with typescript template and styled some component with styled components. 

### React Preview version

0.7.0

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 37.14 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    WebStorm: 2021.2.2
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Chrome: 94.0.4606.71
    Safari: 14.0.3
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Hi @mirik999, have you seen the documentation about CSS, in particular setting up a Wrapper component? See https://reactpreview.com/docs/config/css#global-css. Let me know how you go! :)

**Comment by mirik999** [comment]
Thanx :)
