### ISSUE TITLE
Vanilla-extract CSS-in-TS support 

### ISSUE THREAD

**Issue by tomsdev** [fwouts/previewjs#52]
Hi, are you considering to add support for .css.ts files that vanilla-extract uses? It doesn't seem to work at the moment.

**Comment by fwouts** [comment]
Hey @tomsdev, thanks for raising this.

You can configure additional Vite plugins in the `vite.plugins` field of `reactpreview.config.js`, but I tried it out with `@vanilla-extract/vite-plugin` and unfortunately that doesn't seem to work with a sample project. I'm trying to debug it, but that might take me a couple of days to figure out.

I'll let you know when it's fixed.

**Comment by fwouts** [comment]
This should now be supported by https://previewjs.com, and tested in https://github.com/fwouts/previewjs/blob/main/smoke-test-apps/vite-vanilla-extract/src/App.css.ts
