### ISSUE TITLE
Failed to resolve force included dependency React/React Dom

### ISSUE THREAD

**Issue by wen911119** [fwouts/previewjs#57]
### Describe the bug

I have a `react component library` with the package.json like this:

```json
"peerDependencies": {
    "react": "^17.0.2"
  },
"devDependencies": {
    "@types/react": "^17.0.5",
  },
```
notes that react is peerDependencies(not devDependencies or dependencies), and then i get the error

### Reproduction

preview in  `react component library ` with peerDependencies react

### React Preview version

v0.7.1

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.51 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.61.1 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 89.0.2
    Safari: 15.0
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Hey @wen911119, thanks for reporting this!

It's a tricky one, React Preview doesn't include its own distribution of React, it expects to find React in the project's node_modules.

Would it make sense in your case to have React both in `peerDependencies` and `devDependencies`?

**Comment by wen911119** [comment]
thanks, it works!
