### ISSUE TITLE
Any love for the "css" prop in styled components?

### ISSUE THREAD

**Issue by andyshand** [fwouts/previewjs#61]
Styled components appear to work great apart from this one small aspect. I have a couple large projects that make great use of this property, so a lot of my components styles just aren't showing up.

My understanding is that the styled-components babel plugin automatically converts elements like so:
```javascript
<div css={`background: red`} />
```

Into this:

```javascript
const StyledComponent = styled.div`background: red;`
// ...
<StyledComponent />
```

I'm not that familiar with Vite's plugin architecture or how you're currently integrating with styled components. I've tried a few hacky solutions myself, writing my own transform on the raw TS code, but maybe using the official integration is more straightforward than I think?

Simply attempting to use the example above with the div should give you a simple enough reproduction.

Here's their docs on the prop https://styled-components.com/docs/api#css-prop

**Comment by sandiiarov** [comment]
I was trying to use [@rollup/plugin-babel](https://www.npmjs.com/package/@rollup/plugin-babel). and also I was trying to use https://www.npmjs.com/package/vite-plugin-babel or https://www.npmjs.com/package/vite-plugin-babel-macros.

No luck 😞 

Unfortunately I am not able to debug previewjs to figure out what is going on. Only one thing I can see is that `https://www.npmjs.com/package/vite-plugin-babel-macros` request responded with 404

<img width="2095" alt="Screen Shot 2022-11-11 at 2 04 56 PM" src="https://user-images.githubusercontent.com/15861257/201412626-b32e3be4-6550-4946-b6db-0fe72624f1b6.png">

Could you please help to make it work?

**Comment by fwouts** [comment]
> I was trying to use [@rollup/plugin-babel](https://www.npmjs.com/package/@rollup/plugin-babel). and also I was trying to use https://www.npmjs.com/package/vite-plugin-babel or https://www.npmjs.com/package/vite-plugin-babel-macros.
> 
> No luck 😞
> 
> Unfortunately I am not able to debug previewjs to figure out what is going on. Only one thing I can see is that `https://www.npmjs.com/package/vite-plugin-babel-macros` request responded with 404
> 
> <img alt="Screen Shot 2022-11-11 at 2 04 56 PM" width="2000" src="https://user-images.githubusercontent.com/15861257/201412626-b32e3be4-6550-4946-b6db-0fe72624f1b6.png">
> 
> Could you please help to make it work?

Hey @sandiiarov, please file a new issue so there's enough information to help you.
