### ISSUE TITLE
Not Working with with components in Certain style

### ISSUE THREAD

**Issue by SalemCode8** [fwouts/previewjs#619]
### Describe the bug

when I defined a component like this 

```
export default function Home(){
    return (
        <div><h1>Hello</h1></div>
    )
}
```
I get this error:

[2:46:50 PM] [SyntaxError: Export 'Home' is not defined in module]

but if I change the component to be like this:

```
const Home: Component = () => {
    return (
        <div>
            <h1>Hello</h1>
        </div>
    )
}

export default Home
```

It'll work without any problems

### Reproduction

1. Go to 'visual studio code'
2. define component like this 
   `export default function Home(){
    return (
        <div><h1>Hello</h1></div>
    )
}`
3. try to preview it

### Preview.js version

v1.8.0

### Framework

solid-js 1.4.2

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD PRO A10-8700B R6, 10 Compute Cores 4C+6G
    Memory: 1.91 GB / 14.56 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.67.2 - /usr/bin/code
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 100.0.2
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Thank you @SalemCode8! I was able to reproduce the issue. Interestingly it only happens with Solid, not React. I'll have to figure out why!

**Comment by fwouts** [comment]
Got it: Solid transforms this code into:
```js


$$registrations._Hot$$Home = {
  component: _Hot$$Home,
  id: "_Hot$$Home"
};

const {
  handler: _handler2,
  Component: _Component2
} = _esm($$registrations._Hot$$Home, !!({}).hot);

if (({}).hot) ({}).hot.accept(_mod2 => {
  _handler2(_mod2) && ({}).hot.invalidate();
});
export default _Component2;
```

As a result, `Home` is no longer exposed to the file-level scope. Should be a straightforward fix, although it might have to wait until next week :)
