### ISSUE TITLE
Sub project of micro font-ends app needs change function context before preview

### ISSUE THREAD

**Issue by FatDoge** [fwouts/previewjs#622]
**Is your feature request related to a problem? Please describe.**
Our sub project app will auto change Chinese to a function like window.$i18n(key, {}, chinese_text) when commit the code( run npm scripts to do this).
When run the subject, the main project will provide the window.$i18n function, then sub project can use the function get Chinese or English text.
But when I use Preview.js to preview my component, it can't recognize window.$i18n function, may be due to there isn't main project to provide window.$i18n function.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/20264312/170226884-c60ca2ab-c0d0-45a5-a2dd-3fa9de576fb4.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/20264312/170227060-530c03de-b1fc-4d76-8abd-4f6e738031be.png">

**Describe the solution you'd like**
May be preview.js can provide a global setting enviroment, then I can define window.$i18n function to avoid the error and show the component.

**Describe alternatives you've considered**

**Additional context**

**Comment by fwouts** [comment]
Hi @FatDoge, you should be able to initialise the required global variables in a wrapper file, see https://previewjs.com/docs/config/wrapper 🙂
