### ISSUE TITLE
"command 'previewjs.open' not found" when clicking P button

### ISSUE THREAD

**Issue by timthelion** [fwouts/previewjs#635]
### Describe the bug

Hi,
I get the error `command 'previewjs.open' not found` when I click the p button in a react app.

I see this error mensioned in another issue #408 but this is not a dup of that issue. My NPM version is `8.9.0` and the installer output is:

```
Please wait while Preview.js installs dependencies. This could take a minute.

$ npm install

npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 372 packages, and audited 373 packages in 11s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Preview.js dependencies were installed successfully.
```

I've tried restarting, reinstalling ect. I'm on 

```
$ codium --version
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

The really weird thing, is that I had this extension working just yesterday and it was great! Then I uninstalled it and reinstalled it and now it doesn't work :( . Any ideas would be greatly appreciated.

### Reproduction

1. Install preview.js in codium on nixos
2. Run npx create-react-app my-app
3. Open `App.js`
4. Click the blue `P` in the corner
5. See the error message
6. Reinstall extension
7. Delete extension folder and reinstall
8. Bang head on wall
9. restart codium
10. reinstall extension
11. restart codium
12. reinstall extension
13. post github issue
14. Pray

### Preview.js version

1.8.0

### Framework

React 18.1.0

### System Info

```shell
System:
    OS: Linux 5.10 NixOS 21.11 (Porcupine) 21.11 (Porcupine)
    CPU: (5) x64 Intel Core Processor (Haswell, no TSX, IBRS)
    Memory: 1.97 GB / 7.59 GB
    Container: Yes
    Shell: 5.1.8 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.2.0 - /run/current-system/sw/bin/node
    npm: 8.9.0 - /run/current-system/sw/bin/npm
  IDEs:
    Emacs: 27.2 - /run/current-system/sw/bin/emacs
    Nano: 5.9 - /run/current-system/sw/bin/nano
    Vim: 8.2 - /run/current-system/sw/bin/vim
  Browsers:
    Firefox: 100.0.2
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hey @timthelion, that's certainly a bit susprising!

Do you have any config set up (like preview.config.js)?

**Comment by timthelion** [comment]
`rm -rf .vscode-oss/extensions/zenclabs.previewjs-1.8.0/` also didn't help...

**Comment by timthelion** [comment]
One thing that seems sus is that the activation time is >3 seconds `Preview.js  v1.8.0 

Get instant previews of your UI components, directly in your IDE

Activation time: 3723ms

This extension is enabled globally.`

**Comment by timthelion** [comment]
The fix should be to move this curly bracket https://github.com/fwouts/previewjs/blob/830c857ae975066d8f4150b53ca25acca197f7bb/integrations/vscode/src/index.ts#L257 up to line 181.

**Comment by timthelion** [comment]
Not sure about the startup time still though...

**Comment by fwouts** [comment]
> The fix should be to move this curly bracket
> 
> https://github.com/fwouts/previewjs/blob/830c857ae975066d8f4150b53ca25acca197f7bb/integrations/vscode/src/index.ts#L257
> up to line 181.

Ah, of course! Thank you for that. I'll get that fixed soonish (hoping to make a new release next week).

**Comment by TheAussieStew** [comment]
I'm getting this error, despite the version being v1.12.0.

**Comment by fwouts** [comment]
> I'm getting this error, despite the version being v1.12.0.

Uh-oh, would you mind filing a new issue so I can see the logs?

**Comment by TheAussieStew** [comment]
[#635](https://github.com/fwouts/previewjs/issues/635)

Related to this issue!
