### ISSUE TITLE
Support postcss.config.cjs

### ISSUE THREAD

**Issue by Nyaacinth** [fwouts/previewjs#639]
**Is your feature request related to a problem? Please describe.**
When adding `"type": "module"` to `package.json` we'll get errors like this:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/me/src/postcss.config.js
require() of ES modules is not supported.
require() of /home/me/src/postcss.config.js from /home/me/src/node_modules/import-fresh/index.js is an ES module file as it is a .js file whose nearest
parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename postcss.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/me/src/package.json.
```

We need to change the filename of `postcss.config.js` to `postcss.config.cjs` to fix this, although the `postcss-load-config` supports loading cjs (See: https://github.com/postcss/postcss-load-config/issues/192 ), preview.js doesn't support it.

**Describe the solution you'd like**
Supports `postcss.config.cjs`.

**Describe alternatives you've considered**
Allow users to manually specify the filename of postcss config.

**Additional context**
No.

**Comment by fwouts** [comment]
Hi @Nyaacinth, thank you for filing this!

What's funny here is that Preview.js doesn't handle loading the postcss config itself—that's done by [Vite](https://vitejs.dev), which it uses under the hood. I'll have to figure out why it doesn't work out of the box :)

**Comment by Nyaacinth** [comment]
> Hi @Nyaacinth, thank you for filing this!
> 
> 
> 
> What's funny here is that Preview.js doesn't handle loading the postcss config itself—that's done by [Vite](https://vitejs.dev), which it uses under the hood. I'll have to figure out why it doesn't work out of the box :)

Thanks for pointing out this, I will also try to find what the problem is. Best Regards

**Comment by Nyaacinth** [comment]
I tested this with a friend and found that using Vite standalone can load postcss.config.cjs successfully, but preview.js cannot. And the version of vite which preview.js depends has no problem, it's depending postcss-load-config 3.1.4, which can handle cjs configs.
