### ISSUE TITLE
Too broad error message leaves little room for troubleshooting

### ISSUE THREAD

**Issue by TheYarin** [fwouts/previewjs#64]
### Describe the bug

I'm the following error when my component uses some complex context in my project:
```
TypeError: Failed to fetch dynamically imported module: http://localhost:3140/preview/components/XXX/snackbars/Hey.tsx
```
![image](https://user-images.githubusercontent.com/15931306/144015505-4a517ed3-5c21-4762-a5a8-dcc6d5f52b74.png)

Is there any chance to supply more details about the error, in order to make the troubleshooting process easier? The logs in React Preview's Output panel in VSCode show nothing helpful for this.

### Reproduction

This produced the above error most of the time, but for a short while the specific error was produced somehow. Still worth a try:
1. Create a component to preview:
```
import React from 'react';
import Module2 from './Module2';

const Component = () => {
    const x = Module2;

    return <div>{x}</div>;
};
```
2. Create a second module with an error:
```javascript
throw new Error('some specific error');
export default 5;
```
3. Try to preview Component

### React Preview version

0.7.1

### System Info

```shell
I'll add it if you think it's relevant to this specific problem
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Loving the detailed bug report with clear repro instructions! Error handling improvements are coming soon, I'll make sure to add a test case with your example to ensure it's handled correctly.
