### ISSUE TITLE
Can't preview a vue component (i know the reason)

### ISSUE THREAD

**Issue by HZZformGD** [fwouts/previewjs#641]
### Describe the bug

i cant not preview my vue component. After i saw the devtool console, i realize that is because i use alias path in my component script,  so preview.js can't recognize the path ,  i wonder how to solve this problem

### Reproduction

1. write a vue component
2. import some script or component using alias path like  ``` import someFunc from '@/utils/func.js' ```
3. preview it
4. see the error

### Preview.js version

v1.8.0

### Framework

Vue 3.2.25

### System Info

```shell
System:
    OS: macOS Monterey 10.12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 2.97 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
 
 
(so sorry i can't give you complete info, because I get nothing when run npx envinfo --system --binaries --ides --browsers)
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
no
```

### Preview logs (useful for rendering errors)

```shell
ERROR] [plugin vite:dep-scan] ENOENT: no such file or directory, open '/Library/WebServer/Documents/propose-poster/src/views/@components/Modal.vue'
```

### Repo link (if available)

no

### Anything else?

no

**Comment by fwouts** [comment]
Have you tried https://previewjs.com/docs/config/aliases?

**Comment by HZZformGD** [comment]
> 

So sorry , my mistake , i wll close this issue, thanks for your reply. Setting alias in preview.config.js can fix the problem.  Besides i have a another problem , see the bottom picture (i used pinia in my component, i saw an error in the console)
![image](https://user-images.githubusercontent.com/26340739/171552343-6de3ecc1-daa4-402c-9ddd-4abbb7f91e02.png)
