### ISSUE TITLE
Not working on vscode remote mode

### ISSUE THREAD

**Issue by chenyuantao** [fwouts/previewjs#642]
### Describe the bug

Not working on vscode remote mode

### Reproduction

Not working on vscode remote mode

### Preview.js version

latest

### Framework

React 18.0.0

### System Info

```shell
linux
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Duplicate of https://github.com/fwouts/previewjs/issues/66

Hoping to work on this in the next couple of months.

**Comment by fwouts** [comment]
Duplicate of #66
