### ISSUE TITLE
Hope to support use plugin in vue3, For example pinia

### ISSUE THREAD

**Issue by HZZformGD** [fwouts/previewjs#643]
**Is your feature request related to a problem? Please describe.**

I'm stuck with preview when component use pinia. Pinia requires us create a pinia (the root store) and pass it to the app. it looks like ``` import { createPinia } from 'pinia' app.use(createPinia())  ```.

 i try to search all the issue , none have same problem with me. 

Then i read the source code, i found the reason , vue3 app instance don't use any plugin in the render function. in this file (``` /frameworks/vue3/preview/index.ts ```)

**Describe the solution you'd like**

##### preview.config.js
```
const { registerPlugin } = require("@previewjs/plugin-vue");
import { createPinia } from 'pinia'
 import { somethingElse } from 'somethingElse'

/** @type {import("@previewjs/config").PreviewConfig} */
module.exports = {
  registerPlugin: [
    createPinia,
    somethingElse
 ],
};

```
##### index.ts

```
export async function render<P extends Record<string, unknown>>(
  Renderer: FunctionalComponent<P>,
  props: P,
  plugins: []
) {
  if (app) {
    app.unmount();
    app = null;
  }
  if (!Renderer) {
    return;
  }
  app = createApp(Renderer, props || {});
  if(plugins.length){
   plugins.foreach(plugin => {
     typeof plugin === 'function' && app.use(plugin())
   })
  }
  app.mount("#root");
}

```

**Describe alternatives you've considered**
nothing more

**Additional context**
nothing more

**Comment by fwouts** [comment]
Hi @HZZformGD, I wonder if this approach would help: https://github.com/fwouts/previewjs/issues/113#issuecomment-1018250356

**Comment by HZZformGD** [comment]
> Hi @HZZformGD, I wonder if this approach would help: [#113 (comment)](https://github.com/fwouts/previewjs/issues/113#issuecomment-1018250356)

I guess this comment can help me figure out my problem. (close this comment at first)
