### ISSUE TITLE
"export default" component is not detected

### ISSUE THREAD

**Issue by TheYarin** [fwouts/previewjs#65]
### Describe the bug

When a component is defined the following way, it is not detected as a component:
![image](https://user-images.githubusercontent.com/15931306/144078225-3c4da8cf-8863-4afa-b2ad-55199e27d131.png)

### Reproduction

1. Create a new file with the following content:
```
import React from 'react';

export default () => <div>Hello World</div>
```
2. Try to preview it

### React Preview version

0.7.1

### System Info

```shell
Irrelevant?
```

### Used Package Manager

yarn

**Comment by fwouts** [comment]
Hi @TheYarin, thanks for reporting this. You can get around this by ensuring the function has a capitalised name (such as Component). I'm hoping to fix this soon.

**Comment by TheYarin** [comment]
Thanks :)

**Comment by TheYarin** [comment]
Was this fixed?
