### ISSUE TITLE
Consider adding a default Wrapper

### ISSUE THREAD

**Issue by mayank99** [fwouts/previewjs#714]
**Is your feature request related to a problem? Please describe.**

I work on many different apps at any given time, and often have storybook already configured. This is great as I can start using preview.js in many of my existing apps. However, the stories all start to hit the edge of the preview, making it hard to see any component borders.

![screenshot of a preview of an informational alert that has a solid blue border which is hard to see because it is hugging the edges](https://user-images.githubusercontent.com/9084735/175109146-a595c1fd-b71b-4243-a586-cfc73e2a844b.png)

To fix this I can add a wrapper, but I would need the same wrapper in all my setups. And I feel like a wrapper is only useful if there is additional logic, e.g. theme providers or global CSS.

**Describe the solution you'd like**

Add a default Wrapper, something like this:
```js
const Wrapper = ({ children }) => <div style={{ padding: '1rem' }}>{children}</div>;
```

This is similar to what storybook already does with its iframes, so there is precedent there.

As an additional feature, this could also be configurable via the VSCode extension settings. e.g. a checkbox that says "Use default wrapper if not configured".

**Describe alternatives you've considered**

N/A

**Additional context**

previewjs is a great idea 💜

**Comment by fwouts** [comment]
Hey @mayank99, thanks for the feedback.

I had been asking myself this exact question, and I'm glad to see someone else suggesting it. I didn't realise Storybook did it by default too!

I'll try and get that in for the next release. I reckon a VS Code extension setting isn't needed for this—if people don't want this, they can always create their own Wrapper component that removes it.

**Comment by fwouts** [comment]
@mayank99 what do you think about simply adding a default margin on body? I suspect most apps already override the margin body in their global CSS so that would simply disappear as soon as you import your own CSS.

**Comment by mayank99** [comment]
> I suspect most apps already override the margin body in their global CSS so that would simply disappear as soon as you import your own CSS.

@fwouts Isn't that going to get unintentionally overridden in some cases?

Consider a component library that requires some global CSS. This global CSS sets `margin: 0` to remove the default margin that comes with the browser. Now lets say an `<Alert>` component is used in a story. When previewing this component, the library's global CSS will override both the UA stylesheet and the preview.js stylesheet, meaning ultimately there will be a need to use a manual wrapper, defeating the point of this default wrapper's margin.

I believe this is the reason why storybook uses `padding: 1rem` instead of `margin: 1rem`.

**Comment by fwouts** [comment]
That's a great point thanks @mayank99!

So default padding on body sounds like a good option instead of a default wrapper?

**Comment by mayank99** [comment]
yeah, i think that should work better!
