### ISSUE TITLE
Storybook default args are ignored

### ISSUE THREAD

**Issue by mayank99** [fwouts/previewjs#715]
### Describe the bug

When using previewjs with storybook, the default [component-level args](https://storybook.js.org/docs/react/writing-stories/args#component-args) seem to get ignored. This is not ideal as it would mean repeating the default args for every single story.

### Reproduction

0. Create a component
```js
// Badge.js
export const Badge = ({ children }) => {
  return <div style={{ border: '1px solid', padding: 4 }}>{children}</div>;
}
```
2. Create a simple story and give it a default arg
```js
// Badge.stories.js
import { Badge } from './Badge';
export default {
  title: 'Badge',
  component: Badge,
  args: {
    children: 'A default badge',
  },
};
export const Basic = (args) => <Badge {...args} />;
```
4. Open story in preview.js to find empty badge
5. Override args at story-level to see it works fine
```js
Basic.args = { children: 'Hi' };
```

### Preview.js version

v1.9.0

### Framework

React 18

### System Info

`envinfo` fails to run but I'm on macOS 12.3, VSCode 1.68, Chrome 102.

### Used Package Manager

yarn

### Repo link (if available)

Hopefully simple enough to reproduce but let me know if not, and I'll happily create a repo! 💜

**Comment by fwouts** [comment]
Hey @mayank99, thanks for the bug report!

I didn't even know that was a thing :)

The good news is that it should be an easy fix: https://github.com/fwouts/previewjs/blob/8ed90a0eddbdf417aedaca7e4f549d3b56f6bc78/frameworks/react/preview/index.tsx#L40 needs to look more like https://github.com/fwouts/previewjs/blob/8ed90a0eddbdf417aedaca7e4f549d3b56f6bc78/frameworks/react/preview/index.tsx#L26

I'll try and get that in for the next release, hopefully next week.
