### ISSUE TITLE
deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### ISSUE THREAD

**Issue by MrYanQi2020** [fwouts/previewjs#738]
### Describe the bug

Error installing dependencies

### Reproduction

Error installing dependencies

### Preview.js version

v1.9.0

### Framework

vue2

### System Info

```shell
Error installing dependencies
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hi @MrYanQi2020, unfortunately there's too little information here to help fix your issue.

Please provide the full error message and include your system information by running:
```
npx envinfo --system --binaries --ides --browsers
```

**Comment by fwouts** [comment]
Closing as missing information. Feel free to reopen another issue filling out the template properly.
