### ISSUE TITLE
Add support for Svelte

### ISSUE THREAD

**Issue by fwouts** [fwouts/previewjs#784]
Experimental support released in v1.16 :)

**Comment by jacob-8** [comment]
Glad to see progress on this! You probably already know this but an exported props default value is not being noticed by Preview.js (pro). To reproduce, create a Svelte component:

```svelte
<script lang="ts">
  export let count = 12
  const increment = () => {
    count += 1
  }
</script>
<button on:click={increment}>
  count should be 12: {count}
</button>
```

The number type is properly inferred but the default value is set to 0 when it should be 12.

**Comment by fwouts** [comment]
Thank you @jacob-8, no I wasn't yet aware of this, thanks :) Should be an easy fix.
