### ISSUE TITLE
Auto-detect global CSS and include it where no wrapper has been configured

### ISSUE THREAD

**Issue by fwouts** [fwouts/previewjs#831]

**Comment by jordanarldt** [comment]
This would be great. This is bugging me currently.

**Comment by fwouts** [comment]
> This would be great. This is bugging me currently.

@jordanarldt to make sure this handles your use case, I'm curious what your global css file is usually named? Current plan is to auto-detect index.css and global.css files (as well as other extensions).

**Comment by fwouts** [comment]
@jordanarldt This is now live in v1.10.0 :)

**Comment by jordanarldt** [comment]
@fwouts Hell yes, thank you! You beat me to it, I was going to try and contribute :)
