### ISSUE TITLE
[Feature Request] Allow adding classNames or wrappers to PreviewJS body or HTML root

### ISSUE THREAD

**Issue by jordanarldt** [fwouts/previewjs#861]
**Is your feature request related to a problem? Please describe.**
I'm writing an app with NextJS and SCSS that allows for global light/dark theme switching, but when previewing page components (such as index page), the component is unaware of the global context that is usually wrapping the React app (in this case, the **theme-dark** or **theme-light** classes added to the <html> tag)

**Describe the solution you'd like**
It would be awesome if there was a configuration to be able to modify the PreviewJS root. In my case, I would simply want to manually add "theme-dark" as a className to the PreviewJS `<html>` or `<body>` wrapper.

**Describe alternatives you've considered**
In my case, the easiest workaround is to add `document.documentElement.className = "theme-dark";` into the component that I am working on, but I need to make sure that I remove it when I'm done working on the component.

**Additional context**
N/A

P.S. Thank you for such an amazing extension, and for being so attentive to issues/feature requests!

**Comment by fwouts** [comment]
Hi @jordanarldt, thanks for the detailed feature request and the encouraging feedback!

I'm wondering if what you're asking for can be achieved with a [wrapper component](https://previewjs.com/docs/config/wrapper). Have you tried that already?

**Comment by jordanarldt** [comment]
> Hi @jordanarldt, thanks for the detailed feature request and the encouraging feedback!
> 
> 
> 
> I'm wondering if what you're asking for can be achieved with a [wrapper component](https://previewjs.com/docs/config/wrapper). Have you tried that already?

@fwouts 
Oh wow! This looks like exactly what I'm looking for. Sorry I missed this in the documentation. This is perfect!

Feel free to close this. Thanks so much!

**Comment by fwouts** [comment]
Cool, feel free to reopen if you end up finding that there could be a better way :)
