### ISSUE TITLE
ECONNREFUESED error in my project 

### ISSUE THREAD

**Issue by sanjaysoni5657** [fwouts/previewjs#882]
### Describe the bug

Preview JS IDE trying to render view but getting error in that process.

![image](https://user-images.githubusercontent.com/59286844/183261679-d6841a0b-4ea2-48a5-bf12-25bd2cec46c9.png)

### Reproduction

Open my project and tried preview js rendering.

### Preview.js version

v1.11.0

### Framework

React 18.2.0

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 4.87 GB / 15.75 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.70.0 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
Error: connect ECONNREFUSED 127.0.0.1:9315
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Error: connect ECONNREFUSED 127.0.0.1:9315
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Error: connect ECONNREFUSED 127.0.0.1:9315
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Error: connect ECONNREFUSED 127.0.0.1:9315
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

**Comment by fwouts** [comment]
Thank you for the bug report!

Would you be able to attach the content of `.vscode/extensions/zenclabs.previewjs-1.11.0/dist/server-err.log` as well?

**Comment by fwouts** [comment]
> Thank you for the bug report!
> 
> Would you be able to attach the content of `.vscode/extensions/zenclabs.previewjs-1.11.0/dist/server-err.log` as well?

Hi @sanjaysoni5657, would you be able to attach the logs above as requested? If not, I'll have to close this issue as unreproducible unfortunately.
