### ISSUE TITLE
Persist properties when preview window is closed

### ISSUE THREAD

**Issue by valtism** [fwouts/previewjs#921]
**Is your feature request related to a problem? Please describe.**
It is annoying to have to keep inputting the same values when the preview window closes for various reasons. 

**Describe the solution you'd like**
I would like to be able to close the preview window, and re-open it and have the same input fields I had when I had closed the window, or as close to what I had as possible if some props have changed.

**Comment by valtism** [comment]
Unsure of how feasible this would be as PreviewJS would have to persist data, and I don't know if it does that already.

**Comment by fwouts** [comment]
How long would you imagine the props being persisted for, ideally? If you restarted your IDE or your computer or came back a day or two later would you prefer them to still be there?

**Comment by valtism** [comment]
Yes, Ideally they would persist as long as possible. It's super easy to clear them all so stale inputs wouldn't be much of a problem I think

**Comment by fwouts** [comment]
This was implemented in v1.22 :)
