### ISSUE TITLE
Better properties GUI for functions

### ISSUE THREAD

**Issue by valtism** [fwouts/previewjs#929]
**Is your feature request related to a problem? Please describe.**
Right now, functions in the GUI are represented with only a return box of the type of return. This means that to interact with the props of the function you need to use the code editor.

An example of this would be a function like `ringWidth: (radius: number) => number` where I would need to have the radius prop in order to write a return value like `radius * 0.3`.

**Describe the solution you'd like**
I would like it if the gui automatically populated the props of the function based on the type of the props. Just having the default names of the props would be very helpful for writing functions that reference them.

**Describe alternatives you've considered**
It would also be nice to be able to edit the automatically populated props to change their names.

**Additional context**
<img width="532" alt="Screen Shot 2022-08-13 at 11 21 00" src="https://user-images.githubusercontent.com/1286001/184477592-75b27155-b040-4bf0-8e52-30d7b4f295b1.png">

**Comment by fwouts** [comment]
Thanks for the suggestion, that sounds like a good idea!

Heads-up it might take a little while to implement this (or some variant of it) but I'll put it on the list 👍

**Comment by aheissenberger** [comment]
There is no support for functions at all?
```js
properties = {
  validatePassword:(p)=>p==='password'
}
```
I only get a message that a functional property was called but the provided function is ignored

**Comment by fwouts** [comment]
Hey @aheissenberger, that sounds like independent from the suggestion here.

Would you be able to file a separate issue? See https://github.com/fwouts/previewjs/issues/new/choose for steps.

**Comment by fwouts** [comment]
@valtism it took a while but the function editor is now vastly improved!

<img width="460" alt="Screenshot 2023-03-22 at 8 23 13 am" src="https://user-images.githubusercontent.com/772570/226744025-62561408-9a90-4d15-9214-89b703c28db2.png">

You can try it out with an example here: https://tseditor.fwouts.com/?t=ZXhwb3J0IHR5cGUgSHVtYW4gPSB7CiAgZmlyc3ROYW1lOiBzdHJpbmc7CiAgbGFzdE5hbWU%2FOiBzdHJpbmc7CiAgYWdlOiBudW1iZXI7CiAgc2V4OiAiZmVtYWxlIiB8ICJtYWxlIiB8ICJvdGhlciI7CiAgaXNGYW1vdXM6IGJvb2xlYW47CiAgY2hpbGRyZW46IEh1bWFuW107CiAgZjogKCkgPT4gKHtmb286IHN0cmluZ30pCn0%3D

This is live in v1.19.6 for VS Code

**Comment by valtism** [comment]
Yooo, this is amazing! Just playing with it now but it all feels super nice to use
