### ISSUE TITLE
Show number of duplicate console.log

### ISSUE THREAD

**Issue by valtism** [fwouts/previewjs#933]
**Is your feature request related to a problem? Please describe.**
In react components, I will often throw in a `console.log("render")` to get an idea of how often a component is re-rendering. I thought that I was not getting many re-renders in the Preview.js console but when I looked at the console in Chrome it was clear that there were many duplicate calls

**Describe the solution you'd like**
I would like a badge next to duplicate console.logs to show how many times it has been called.

**Describe alternatives you've considered**
At least we could just long the same line over and over. I feel like that is better than hiding the number of times the log was triggered.

**Comment by fwouts** [comment]
Good point, yes absolutely!

**Comment by fwouts** [comment]
This is live since v1.19, sorry I forgot to update this issue :)
