### ISSUE TITLE
Readed about your IPC Problems

### ISSUE THREAD

**Issue by frank-dspeed** [fwouts/previewjs#982]
i saw you got IPC Problems i will pre pare a PR this is just a note for me and you

```
const subprocess = spawn('node', [], { stdio: 'ipc' });

```
It is worth noting that when an IPC channel is established between the parent and child processes, and the child is a Node.js process, the child is launched with the IPC channel unreferenced (using unref()) until the child registers an event handler for the ['disconnect'](https://nodejs.org/api/process.html#event-disconnect) event or the ['message'](https://nodejs.org/api/process.html#event-message) event. This allows the child to exit normally without the process being held open by the open IPC channel.

'ipc': Create an IPC channel for passing messages/file descriptors between parent and child. A [ChildProcess](https://nodejs.org/api/child_process.html#class-childprocess) may have at most one IPC stdio file descriptor. Setting this option enables the [subprocess.send()](https://nodejs.org/api/child_process.html#subprocesssendmessage-sendhandle-options-callback) method. If the child is a Node.js process, the presence of an IPC channel will enable [process.send()](https://nodejs.org/api/process.html#processsendmessage-sendhandle-options-callback) and [process.disconnect()](https://nodejs.org/api/process.html#processdisconnect) methods, as well as ['disconnect'](https://nodejs.org/api/process.html#event-disconnect) and ['message'](https://nodejs.org/api/process.html#event-message) events within the child.

i guess:
- https://github.com/fwouts/previewjs/blob/main/server/src/index.ts
- https://github.com/fwouts/previewjs/blob/main/integrations/vscode/src/start-server.ts
- https://github.com/fwouts/previewjs/blob/main/integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/services/PreviewJsService.kt

is the right place to integrate

**Comment by fwouts** [comment]
Thank you for the note!

An additional complexity here is that I'd like the Node server to be shared across multiple VS Code workspaces (to minimise memory/CPU usage), so it can't be a child process (as I understand it, it would otherwise die when the workspace that spawned it was closed, meaning the Node server would then be offline for other workspaces).

**Comment by frank-dspeed** [comment]
No Problem again but that already sounds like you should over work the whole design of the extension :(

Or at Last write in the Readme that you expect at last 16 cores on the cpu and 3+ ghz you can not start as much NodeJS Instances in a efficent way.

Sure you can do that all in code but no one should do what your doing there let me show you what you did created out of High Level View

```
VSCODE => Extension Host => Your Extension yes it is a Extension host but without a protocol or any design for distributed Computing => Your parts that you call server are Extensions. 
```

And what you should create should more like
```
VSCODE => Extensions Host => Your Extension (can include a sidecar nodejs process but not more)
```

You Should always consider that is a IDE when i open big Projects and your Extension Eats up my Memory my PC Crashes and i loose my work that would not be the first extension that does that. 

## Anyway Using IPC

```
VSCODE => Extension Host => Your Process Manager => Started Processes via spawn IPC
```

Is Still the correct Pattern you need a Process Manager at All you can not Leave the Gost Processes Open 

I Would say as you got not that much expirence with that use "pm2"

It is a NodeJS Written Prozess Manager including IPC

https://github.com/Unitech/pm2

```
/*
The online documents were not very clear.
http://pm2.keymetrics.io/docs/usage/pm2-api/#send-message-to-process
https://stackoverflow.com/a/35504369/3386260
https://github.com/pm2-hive/pm2-hive.github.io/pull/117
*/

// Sender
// The sender can run inside or outside of pm2
var pm2 = require('pm2');
var neighborIds = [];

pm2.connect(function() {
  // Find the IDs of who you want to send to
  pm2.list(function(err, processes) {
    for (var i in processes) {
      console.log('Id:', processes[i].pm_id, 'Name:', processes[i].name)
      if(processes[i].name == 'scout') {
        neighborIds.push(processes[i].pm_id);
      }
    }

    // Call this once for each neighborIds
    pm2.sendDataToProcessId(MyNeighborId, {
        data : {
          some : 'data',
        },
        topic: 'some topic'
      }, function(err, res) {
        console.log(err, res);
      });
      console.log('Ids to send messages to:', neighborIds);
  });
});


// Receiver
// No need to require require('pm2') however the receiver must be running inside of pm2
process.on('message', function(packet) {
  console.log(packet);
});
```

**Comment by fwouts** [comment]
Thanks for the suggestions. I didn't know about that particular feature of pm2, looks promising. I'll need to check how it plays out with WSL as well.

Just to be clear, the current implementation ensures that, aside from VS Code extension hosts (which VS Code spins up), a single NodeJS process runs across all VS Code extension hosts so it's as efficient as it can be, keeping resource usage minimal.

I'll close this issue now as I don't plan to change the implementation in the near future. While slightly less performant, using HTTP enables other use cases such as supporting online IDEs.

**Comment by frank-dspeed** [comment]
extra note to stop a NodeJS from Crashing if the PC does not crash listen to unhandledExceptions
